apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: foundry-secrets
    namespace: foundry
spec:
    secretTemplates:
        - name: foundry-secrets
          stringData:
            FOUNDRY_USERNAME: ENC[AES256_GCM,data:5TXXD4HCXJe/h48=,iv:rAJeZKDLVDzpTAfMZGfYqetRG2eGqVeBlmGFJ7Ef45g=,tag:SyBgJyORlQSLakiMeu+MhA==,type:str]
            FOUNDRY_PASSWORD: ENC[AES256_GCM,data:in8zOkI0efBEH/Lf1PSnMBHHTA==,iv:NU7JC83bxUgfDkbWH8qrrYbc5Ubx/RTfrVjJPMOpZfc=,tag:yKSD2tdf+V0VWzVVL5+3vQ==,type:str]
            FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:6ejn6yz1WgbDPSfgBg==,iv:T0scGRiq6wTH55yDDkeHwORGWpsFuHF0TERsK0DFe9A=,tag:t6od8kz0r55qovP7NVhpmA==,type:str]
            FOUNDRY_LICENSE_KEY: ENC[AES256_GCM,data:+R0ZUg9JxbP471v5E3k8wL4hwGtK34RFgxBaBX8=,iv:3T8UGbMkIeFl/E8zn1bN1L+NJHzw6cjhprBVdn9l36c=,tag:+k/MQdpEZY5YMVI7DhcXKA==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK2I1SHdzZmFSZGxwRUhK
            QmlVd0tjYzYvKzVzTzJlVnR1NHBQcFdDSXlZCnFpc1phQWZXYTFiR1ZVTzNDeGFI
            K09pd2NkWVd1MXBiV01oT3RjZkpaNkUKLS0tIHV4ZllTTlBqNU56RXRpUHFwL1Bo
            UHpvakVDYk9HdEQwMUY0VkdMSFU0MDgKQt86G0u8ySDy8yV/zGwp1lOMMIK08MbH
            WaBVpFrysZDC2aOVnkNOQuu07oyRto0zIJL47NZa8pbwQhLWB/8Y+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVWl5RnZpT1FRRkx5clha
            bXN1djRHL1Z5QXYrdEk4eGpsUzdlcWRRWEdZCmh2SkJHc1RmSWpOQkI5dThxZ3Mw
            cEVZalBDZDNjbzByMEl2bUl0USs1SDQKLS0tIENmdjBtdDRvZFBJRm5DRi9OYmVK
            YTRvbTNEMWVLY1FlTFROYUZuK3dJeE0KZipaqzRBi2mHe/S9eRKUy3iDAoL8Lvc2
            kt+crTtHsk028DJfH+HmUIXXUh6ie5mi+wcCi9KlNhyOPlqS0L/eRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UTE5NTJYZVhldlh5NGdL
            NnVoQXdUOVJ4dWxvRUpSNmRra1hWM2xLNGlrClZ4aXo5MHlIZUFOdnhMUDZ1UGVZ
            cnFRT3F3djRCemdHd2xkOW1lR1FLRjAKLS0tIG9DTEw2ZWFtbFZUWUFQUHEvaWtB
            ei9hMGJBc2hBK3loYTQxRjFHeWFHb3cKMSMgMWDo+YHAN6Laf7wRmxGcz8feM1cs
            Gy0OYOypAZkTaZDhFiphXxvywDd31maAM/ysWs6fpU4CoUDPO1YVEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdVRsWGJoNlJWSDgvRHhP
            Y2Q3cDZza1lJRmFucVhHU0Vua2VyR1hjNmpFCkhpcVNINjkrUVpKa3Rsaktmajlx
            YkgrNWF4QzJTWTFXSG1wMVh0cHZFSHMKLS0tIGlhb095V0JsMHJEVFAzcjMwc1hW
            Z3RuMThYUmp2aEpNR2duVHQ5VE9xRTAKuE1SUNbKM+AmnWmg/onejpQZ5v5Xl7d6
            2w/exgkrjoVAQHxfNmaPVIDksHj0P/aNnjm4zhjUqeQIem0wOwEJsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WkRKL0xscWhST1lmM1Bv
            Y2Nud2k4Qnp5cVpBdGZvQm1wNGpRL1hUdGt3CktKSnB3N0h0Q2ZNMWhraTlFb3Rx
            N21mOXN4YUdhZCsyMWJNM01zSTdyV1EKLS0tIDFrNHQwYW9DV25Ha2dSdGd6ZzBv
            QkNtQ3hjbzlrbWRWNlhaRno0UnJFU2cKEMdCki0PUb3zdqCOBm7a7Jj9lJ1e0cht
            TM15phqu5RamPHl8auX77C3n/9HkG+iIrDJaezyD5sXS5Mbz/szzxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK1IweG5LYWhPVzJwSWpx
            a1JsY2dSaVd0MUhVQ0ZPOVFGcngxdUhUQVF3ClkvNzloaE9ES3hTaU96eStjc2hv
            TFB2TjVLb1A1eWloL21nL1FzTGpOZ1kKLS0tIFM3RnFSUEVPZVd4WXFMK054cHBY
            SVlZYS9Ra1ZFSHpJb2pCTmhEM2ZoUGcK/Hh9Wpm5PHCS9n1g+SOUO97RTVcXmxDD
            VMJb5oI/KIU1ze5qtvPF0csDilvfc75AAI9fM/x8vK6alOFlGjdtWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRjVpK096UVlBeTF0UWUy
            WnNrVXZod3ljdHJwbHhGVEFRNGlvcW5ra1JVCklkSFZRdElBcEM5VFpWRnpqcDBp
            blRIT2lLVUI2OFROaEQ5U0NMbTBhN28KLS0tIE1YOEp3UW1UczJyWGZ2c2h1RjBB
            dkozV0RXQ0ZraVluV2Y2MEJXWnE2UGcKzpFI6ziHcsq6hZ1ujZexzLbDrq2iAU+R
            BgbP/gdpRZ9Bf5NOtFkHRSxJD3UH69V5zhGM/+Y4KRVk0mt6U7iM1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T17:10:48Z"
    mac: ENC[AES256_GCM,data:Fg7ey5HygWnm+Q0KC2N2yyrkDxMHF6TkTGVRH4HTUFvUMohlZnScxqYEOQfyBFVgxDwA0DEkr5412vgMdelY/qGWFnOPQ2tHGyM+0eFjJqIMeqeGwxfeBXIwfsg9dvvc5+XvUTPo1wmWA8U2azZsoYUXlajstOTdV3lIcs4LGGM=,iv:vS95IqYHOEPtTtZkpRvEV37dcIICKDEh03I3u8jBvtk=,tag:I+O1S4Zb3JvfgtOr3MyRSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
