apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - public-ingress.yaml
  - tailscale-ingress.yaml
  - foundry-secrets.sops.yaml
