apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tidewood-app-secrets
    namespace: tidewood-booking
spec:
    secretTemplates:
        - name: tidewood-app-secrets
          stringData:
            DATABASE_URL: ENC[AES256_GCM,data:/WkZQfJEv74G2EwiUDf7wZb7ZuSB4ETZ2ZajwXjWcW/iLDqzTd7YaUxmBb8NCGw3MxA0jjnBSRcLtvEkqge7OvyTFzvDAg9PuEpoZikfu9l+3W7cmGcHVirqzIcIgftFbV+uSTX0D9iWb/qqQ6n3yeRigebcyDRF31Fj,iv:Q3URNecLoSRdBEdfBG2SIDt68Um0/gzhM25jmzuvMxc=,tag:33S5fzOk2z2eFnbosG0htw==,type:str]
            AUTH_SECRET: ENC[AES256_GCM,data:iNwlASyrqW1bAEouFKeALVmV9TYWn8vr+pmiVyU8r8wnCHmST7EHHP9T/2IaVC1u3zwnAsPyq7bIxVmyS4728A==,iv:4lOOQGifn2mVVcvtvfn4MafXhHQbIMZZLYNw85e0d5Y=,tag:Yg9jobJLNW1+KaPSk9u5jA==,type:str]
            AUTH_URL: ENC[AES256_GCM,data:aCmUsPg7qaXIPBvZK/la6+GxrMuSA/Gpr2jYpQW1bnA=,iv:sPG5Pl1saVdLM2pfdk+p9btn/xg3lQd8giqr1DMH/z4=,tag:XjaC8fn/WrYaYZx+dqj6kg==,type:str]
            AUTH_GOOGLE_ID: ENC[AES256_GCM,data:Q8+WcrE7P8zPECOjRSZ2xytyGkKUd0qCYaYjbelWeSIBqn9hsgIVTNMFrdarXvPVyFp7OXtjChnaI6K21dfTswgE82XhO+2o,iv:rEMZfb9zXX5/m2NrF1YK///y+l1gQgMxrnolqno1uOM=,tag:EaTTOA7+WTEFbzfXyZgiaQ==,type:str]
            AUTH_GOOGLE_SECRET: ENC[AES256_GCM,data:Q0S/UaAmV1aLsVWujpI/D2R9iUHe37+kwi8I83ZFFKU1j8Y=,iv:RTR4ntxAwG5EjA/TTFdEkmIbXMCPd0R98oTvuIsw4c0=,tag:itMtyLsdRzvKCebVNqiTCg==,type:str]
            DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:p2HZWBSsMctnirawbqg7H/u6USKXJmG1l47ogIhET7Zp/F9ve9pq77ZByhxcgYB/EM0/+plWS5PLXbcIgImzNTDJSvH7o9CddWMVB4GbBWb1BIR/uEWW,iv:3X8bZRc3TOGMj6BmpwWbvT9EHK6k/dPzvkzQXZ/Tq7M=,tag:FUgG/nPgL/c5tOXdHaE6yQ==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZnJIdTJJYkN4N0UxdlZm
            SERsMy9sT0xaaHhCR0xPZjZNN3hqZE9VUEV3ClZNY0ErSXVKOEk5VklZTVFhb2pQ
            elFYYWJFcGhXSEFESXVBOGR5aGNKNXMKLS0tIGttK1FZTHhzOWpEdjcyZVkyTDhS
            MjJhdWlSVW1mYk9GczZmZ0Fwclp0OWMKoiup8gI1qbxAbzpR66l4W+33X4YleFyv
            IJBZIsEXDse+hEzcrCEK8TdQrSqpzkEMqJ/kzJ8HW1jv7dI3SBwp/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYVNYbUJhQWZDRk1pblBi
            WFdJQUtaczg1TWNhQTBlT1ZoclNsRno0SGxvCmFqb1RucmdNUFc4dHZZRzUvdDdn
            M3V6Y3pKZGFKS0NaSHZiL3dTcTFXRVkKLS0tIGU1cHhTNzIxdkl5dXlPYlRlR2VN
            cUprUUxETSsvcSsvUmxVa0NodDJ6TUEKQ/nS+CAH/rzpq9ZISTMnnzB9nQnZbZar
            cWZnyWeJ3vwto4WpbzANFeiURvOTi24yzNpytz1vucLsARTMD7qMag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2dub1JWWlBPanUyMnor
            V3ZiRUFuNUZNS0paYlBuUjIwcWgxVDdneDF3CnI0dDd2aG5BMEsyS2hReUV3dmRB
            THMxZlJYWXZUZFF1b2xKODd5MGVTVmcKLS0tIEhoTnZhY05IT3Q4TElGQllXWm10
            RlAyRnZTL1JqcVNGVmF6WlJlL3RoZDQKETcdrWxcGjszWHWpmI0RGsOo9X7lFOq6
            Rfe//fAk9JBHQrnnloYrDt4r9/N44YsvR3F7FFdk3kNpU1ndUeVyUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSGNJc2hzeWpaWTcySVhO
            eHV0MkVkeEJNdjc2WStZQlczeHZMM2NDMFE4CmJ2UkQva0FqM2tla09qcUorVko3
            L3dZaTljRGVoWW5rb0tmRGc2MXFMVDQKLS0tIEczaGt5L1YzZ0ducFBDWDRkMlBw
            Zit1dmo1NkZLa2pxbDZxaGVYWUQwZ1UKA/Izpk+xlLLcubAh29TOoTEiFJ5h4I0y
            xsPims21ANuQ1qPV/M+5d2zsT/5zqhZIUX6a8WeJ/waAN0MpUs+7Bw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaytjbUdVOGR2OVpkVGZO
            VHJuM1hVTkFJaVVodkVlMDhTRG9adHpqWlZnCnNJU3pjd3VhZFJ2bjJIUmo3cGFs
            OEUxY2xOQnRTa2NPaFJKVm5uOGhvdlEKLS0tIGM4eEROLzAyV2VKOTdLTEFEOUIv
            YW1nMDdsZGFXaEc4S3ZmVThZMWpMS00K6VgTXgs9yyYR5UpGpixCU1hV0IhH0/F2
            h01tHnsygBfZcLKAudUka1f5sOXBiVyO3clRDz+z/AMahysQxEsXWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUnVsMEY3UHJyemNrQlg0
            VWZvRjBhc0VOaXd3bkRUUVlDWk9BWFdZc1dBCkZCckJWTEZ5cUNxT3I1c1NIZFdi
            eW55cUlBTnVNQ0dVQlFMeVZEOGJiSEkKLS0tIENNcjBvYklSelZsOFQrRlhxZERT
            d0ptYldVSytjZ0tlWjZtU3IyQm5BUlkKupanZu/QeLGr7A+IKAfnylkahyO757yZ
            QeuIboyfcdLEYcRhB9PVnWGg4NLVShOunSsu1yOuXUjOXOPDQC/8lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVFhJdmF4eGhHWkJKbnVl
            VXhVellQOGpYQVA2TStlNTc0VCtETG5zaXhZCk1UOXhBdWp0cGhvM1dmQ1IyWjRl
            WFJIeXZxcmRESWhySDRFaTBMRXg2OWsKLS0tIGRPRVAvWFFWVWJtTVZ2ZWZCNXJF
            cnFTL1k2Y3lsZVlvN3R6d0RNMGNzMTQKrUXBz2KC5Qb6BWR1dQiu9QohZ6iBtxYk
            FJ2mfvzanprke2AYL+1f8a22lB/q0HuEYK4zPEGC8o82fNJsusX7mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:23:49Z"
    mac: ENC[AES256_GCM,data:yiL9JbR8eLaj2GTAtibBtQZ2neRQEV+47uc6skqwIsvWjk7LxPXd+iSyGaMOD/ebR7rGVrFTV1ImbDkIjLPOyizZ0EF725LweFDmqptVx+qPQ8385IvJ73aoFSzd6wX+nkNOqPjwY6lhOarCWyASHVDFJEFw5mqJykkENPoRmBg=,iv:awYYUupSYmRvJ72gM5d9eawZ2nizp/q1F0GEelmDq6c=,tag:qD99CBJVQsBueZoR7+5d+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
