apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dockerconfigjson-github-com
    namespace: tidewood-booking
spec:
    secretTemplates:
        - name: dockerconfigjson-github-com
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:iMjxoU8brksXez0UqogqGGnZ5OQt2KiMisO1dJClTbYxcwmd1i3v5zNHWij1sisL3Vj0XeqonAw7Zar/ufkui7uIRW1mATaQMJoyNTCXr/Gd1rrNgJMJ425WAo2FD+kBGA/YFaHI4Grl,iv:UxaLCFmVzzM2IDnp6lx6JZKn2eq/3X2cM3JctjHkNCo=,tag:b97hrYzD/RMxZTnmYtJzig==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPS1Fmb1YzN01TTXNWYWdz
            MTJLcW9hYWVmMUsrZ1RrenB4UCtRaWs4WjBNCjhPeFh1dUUzU2IvcnN2WHpwcGta
            VmNET21IR2MzSlFhVmJBbkc3Yk5nY1EKLS0tIGNFZGZYTUw3Z0hOaXNybUtNYTFl
            RnJMUURFUDVBYmdJUzBoVExlSWVKS0UKRajzpNT0h62XeNRy2vMhKccOtvmB9QQb
            DSLdAk/g5S8ollcjmDTpz4s7avKGUjlLbet6ucN/p85hgxAwD2d3YA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaW9sOWlhdFM3UkZ4dWln
            c1hlaXZCRGpvcHQvcW5GN01RdUlENnQ2cGlZCk5abDVmbk1zNGdMZzlJVC9pbUlw
            OUVMaWJySFptMVA3SlhoOVdCTlpLY2MKLS0tIG00dlVLWDN3andzUVlHODhFSmZN
            Q2Y0QmMxMVpOVE0yOVh0b1BrNmF3bHMKs72XmvDH5pGW41fslmP8JT22lLILdtYP
            LrO561/5pr1Z8EhcqCKCsQY2aVbGiHsm31GBo/rXgPjLka8V8vyU3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTEp1R05GQWcvOTJzUTdj
            aUdFSDJ4NitMQUVDamNtWHpNQlhGN3RxaUN3CmFVaVhTbXdwTldGeUdMUXR1Y3Bo
            MjZPb0VQcHMya01Sc2JyTVBRZ0hBa2MKLS0tIEtkNTUxc3N2MlZCNzB6OVUvZ0l4
            V0ZYMUFvQnpwaWtHOUN1YU03ckErdVkKR+ivRXyyiHYptINzIH3+R9n5u9Zh4ulB
            OCkfYDYf1xdAFvtAKZOWy7EwMfLHLv64kJQKS6zpJ6iBSgckjrGTTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaWhMTFZQU0lpbnp3a0lx
            cUZqVHhUVUh1ZlRya0RSdXd3SFBFWFd3N1NvClRkV2dtYU53dDZSSHNvQUl1eWJs
            OTdDaVRWcGJZMHh3KzlsSmdkMXZ1MlkKLS0tIHA4MDRBN1NHZkdkWklKc2g3ajNo
            aHQzREY2bndWSlY0Q1hYTGVQSXNCWTgK/4vJJbNLICzuZa/dTVePwhZq9wgYiIEc
            zp7WsUyAJOUy6Inn7S1A7/WTOE2/RVDN+M8b8gsMYRDlVVnvRGy14A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRkVqMlZJMnhjSWJWM0tI
            QWM5TDFWak1ZbEdDV2FwMGpoTVBUdUpKaHhvCnBEL0xQWmFtejdqNk83TUNEeEp0
            Nk4wT1Q3dGtKNHlra0JxMk5MU2hYbkUKLS0tIDZJa2dsVU9BUFdMTXVsZ3JXUTRk
            MUtvWkVJbGg5SzFDYldhUDBUNlA3RFEK5x1YcUJtMChQgMmRszIHo9xtWmu7Dtu6
            DVBRaO1nmlgn81qQ9gsvZroBOtdIDdSlkHszSlYUKgd8n/jorRvKHw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZUZ6RzJYQlhkaVpsRHNr
            TURqeDc4K0tiU2ZlY0NLekNJdEtqNldqL1dzClQvL2VUbEUyb0RRVDVqZGUyWWVr
            WWphMzNXMDFlZERsWWh0R05tSnh5WmsKLS0tIFlYM09iVmc2aWRhZ1dGNGhkU3A0
            WWxuZThNUWc2WEdjdjI4UlUrbjFBVXMKew/EuXhqTHeBktWpOUrpj9aMHWFRZQNv
            jmlvr5ABfgpfm6F/sHVk5bWbGhacJvKi2ZQlVzQOIPq9z9km3AttBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY0hiYzMwTEUyQ1pCTHNT
            QnRFZHU3SEdOOS9ENTlxR0hyTFVMeVlCMmd3CmlqOVlDd2FaVVA5VEZxVW5XK05o
            R0dnWklKK015aVk0Z0lBZWxZTFFYOG8KLS0tIEFxc3lNUGhtbng5YyttR0c5M2h5
            Rk1sTis2VzNBcGkrTnhwdWxNakMyM1UKeUJ37chUlwwak8962PEHBWE5CdHgzFDy
            xjKnkKmdZig9ivArMtVz5mw1f9mRFroZl/jvRRAfdAcVabX2t0mroA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:38:20Z"
    mac: ENC[AES256_GCM,data:9fV2RGp1gD8qlc+67yhEh/zYfOMHN06Q31dVURMb8K7zAUjdHIRE0fmccC2go294cpR3xTetg5AjYdZSXDEpM0TyqEwrDaD7rvZueyosedkdCw7MrVekjXetYxQZezn/jDIw7ciWJV5PdB5tqjrIZIHUwzqR++4gC3Rzz1Co51E=,iv:YC6iRvrrfYJfF50hXdEcH0vhU4wo01+Dz5P0UDvqb1U=,tag:4LLaxD+y55BZefJXTjpjRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
