apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - tailscale-ingress.yaml
  - homeassistant-egress.yaml
  - cronjob-reminder.yaml
  - app-secrets.sops.yaml
  - ghcr-pull-secret.sops.yaml
