apiVersion: v1
kind: Service
metadata:
  name: tidewood-booking
  namespace: tidewood-booking
spec:
  selector:
    app: tidewood-booking
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      protocol: TCP
