apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexispaul
  namespace: alexispaul
  labels:
    app: alexispaul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexispaul
  template:
    metadata:
      labels:
        app: alexispaul
    spec:
      containers:
        - name: alexispaul
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: dog
              mountPath: /usr/share/nginx/html/dog.webp
              subPath: dog.webp
      volumes:
        - name: html
          configMap:
            name: alexispaul-html
        - name: dog
          configMap:
            name: alexispaul-dog
