apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alexispaul-auth
    namespace: alexispaul
spec:
    secretTemplates:
        - name: alexispaul-auth
          stringData:
            LOGIN_PASSWORD: ENC[AES256_GCM,data:dDVz5czovKVAO81GiQ==,iv:f9/37xDAc/UAX3z8KfWNX6WdHy1aPCBq/FOlLGzTnUk=,tag:YKcyUNyVh2P8EyqYqhYcRg==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeXVzdkdvQUZmSU1GenhO
            UDRXTnpsNDFxeEladStxMURGTlh5ZGp1SUNnCnJNMEpxbGZ1bm5KOHNTUDFJQzhy
            ZERhY0xBQ0I5RjJHK1l6RXRrbi83OHMKLS0tIExPQUNzSnNJQkJMVFdSUDk2Uk1x
            TEdldG9QMThPd2hEdWhBUlE2cnUvSmsKDux5RPfiau0uQKpfx/yCYN1+cfxdAD0n
            aaDwpwdiMQiQ4Uv1yIfyoCTfxPBzkpjjmP1gOlhhUtMeUrEC4gVFPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRm9RSk0xZzZ6S2svNjBE
            UzlJcDNzaCtSSS9FZ3hwYldmTS9lWVdqRXdrCjJoMytxb3pHOGlGQjRnU1NtdlU3
            Sm83d1NtQVRmM3lhTHFBcVliSG51QUEKLS0tIE9HN1pMazdsUU5wNDRYZHVld3NC
            RVhwUVg4bHZXVjJ0dUJzODI5dDgyQlEK5CI9oA9dKBPyqPbZ+cufIZqI717pZbFy
            Sua0nKOiiC3UnMBW7QMo3MkuocFNvgsioYLM6wMrzB2cIBdbkgw3IQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdHBxRFhpQ3RPNG9jRStx
            SXVUdFFCWlc0Tk01bndTeXFMR0Z2dm9EMXhvCm84S090WVVLMjhKWkZhVjZyY0Vs
            ZGxrcHQ3SHNiZnE3d2lDaW1qN0RZMUEKLS0tIGIwSjdIK3orUUpZRm5FeHorWlAr
            WHdGZlVzdmFHVlY3TjFRcHE2RTI0TkEKXoFncscF9Lt1x2VwXSuutKgrGx1WEcSx
            mPgGUVwvitB0LibWJT0u+qrI39R19X3ZZk3p6Lf3opTqhAUYKYhSPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ1U3aE1KZlhwUkpxb01h
            RHA1elBUb3hmOEI5UHdqVzdxMUFGRXMwNVFzCnlHZ01PWjh5MCt6Y3c2MHlYQ3Q2
            WUJTZER3cTYyK0FqN05IS0RQcmpMT28KLS0tIEw4R3E5b3U0VC9YcE8yNHk0ZXB5
            UWhMQWN1ZEo4NUhJZitYTWRZSHZnL1EKfSa7qvfmbEfmP39NzDUsNpXf2KLaUZ/d
            2vZGRujZm/MLrH7a/k4H971+Mo+7Wz7dY6UP6gIAseL5KhpRRV3N6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UEoyOXpibkhsMTd5a3Bv
            MyttaEFqVU9qV3RVQ0p3M2RBdzdOS2c0WTFZClF0VVVkcllZS3FxTllOeDB2MWJL
            MnpYRWpZelRMK1RiQ0JlZVVxeElNQW8KLS0tIDRKaXF0bjlzS29lak1qdVBwTUZq
            UjQvUmNQUGhYeVJXNHNCSEhxU1o0K00KUatEqgdjI9AJ7xRxAFgm0HL1fOhuWmV4
            Ze7A6HyluziDsHf3X0j5acvJKWvgprvgVxZwBbeOXxKYq03n6WOR2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUUdDbFpIandxZGFTWnV5
            amtXWlkzK29rL3U3ZHNnYmVOeFNHdDZhWUZvClE0SUttM3dtNEZtcTh1QVFtUWhv
            aDRYaHk0QkJSc0Z5M0hsaVJCWFhRdVUKLS0tIC9SZmsweTVORldhMkswZDVGZWdz
            bzFsVkJ0VTFsTUhVN24rK00xNXY5b2sK03Pyzi1711pN/OBccexWk/uakUGVH1by
            P/i9nS8dCpDmIngNvZ+E0vMzcEDheNi1XuV2fNw47bIxvV9s99/4wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZThiSUpISndZS1U0TE5B
            OUcxRGluZ0tKN2doWjZyMklhbTVHdytnUTJZCjhQdUI2NWF1TVRSUndZUmhMNlFL
            UjJhZU4rVFlKN1dqbnczNnZlUnZReWsKLS0tIEY2eUJObkZqT21iVWkrbkM4OVlr
            cnJaRDBETWVkdTRCaWpOTVN6WmZ5WXMKq+rBCenjKpkVrFZTy42uOnuF4AbtKLyL
            ae4SLJmk8ATER2E6MThmgasVKQk3gYzB0ZlLXMbFT68bPnc7s8UtRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T06:22:37Z"
    mac: ENC[AES256_GCM,data:j8h15kb74noA4kVh1l1364oCPAR21wE0NF1mEeoaW7rd1BQxEf/IJXsquae0ds6bLJbDIvjee4LtPVy+lIUWhklmszMVO+gtx+NOP+Y5mv4M/IB+oPbyvTqA6Jl2lm+vEH5ZnU1rapTbUMs/5KeeQkigUCFsV9V5d0jaQpYM7NU=,iv:IFc8wIE4Cf22tP4Htz3j1i3u/wdo1/eu/jWiTwvRAzQ=,tag:kNPCFfl2PzNdzG4etJO5pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
