apiVersion: v1
kind: Secret
metadata:
    name: alexispaul-auth
    namespace: alexispaul
type: Opaque
stringData:
    LOGIN_PASSWORD: ENC[AES256_GCM,data:kls2L3/JYJERFACCXQ==,iv:fhOw0i1JzcpIBTpdW49KPSpFMsbxgvK5ErdhcP7XuWQ=,tag:bKGNiqL/Yu+Yi1V0qY+Ywg==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWKzN1V0dQVWNORE9PRklO
            eTlqNDJKSll3RmhPY3NGWUlTUHhVWC9HNVFJCjcvZVluVmJGWmhtaXhBN0VnU2F1
            UXlLc3g4TnFudzYzeHhUdXJDcGl3L0UKLS0tIENHVjJ0WU1zRVR3SXEvbTg1Vlh4
            VDIvQlJMWFUvQS9sU0dYMWUyVytzc3MKguEqiUzFGyGs/lb6oNOkZsCk2Zn2wdbl
            YpGBXfl2saaIIn5iOsOILSgGwhe7KT66aqd4ODZE/8ck55r6FkP6rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a1pHZUhqTHMwMWZ3YlZ4
            VHRPNHdpemxQeWRRbzQzaEs1U1E3TlByU3pnCklXd2ZoQTd5aHJ3M1d5L2tKNncz
            LzhyUWVscFFnS0tKZkhHMytQUHpZMDgKLS0tIGhwczJ5V3k4SjdEbU9qNVlwbVVP
            RENaVzYzU3YvbXIxejc3eDR2VkJHaVEKFydldhNh8lEs7mUNaWJ4pXdN8/In/E+h
            AbjoLCpHvRsn6dTtnKoE6kdC7KCpk8S1TIfxwsUy33+Z+59tR8aUpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4S2NlRWdsb0JadndadUhL
            WkNQK3BSZy9FU1ZpMElucWV3U0thSmFzUUVnCmxQdWwwWDlWNG9xRzBRNFliQUdZ
            TDFkRWpUYlhPTkNPWU83ek1OVEJCWFkKLS0tIFQ4U296Ujc0aFhXUjBQV2M4dUJL
            RGRPOCtLN25tclRyYjBOVUxWaURwUWsKOnXPRGQsml180oG7HiowPjCEYZsLsCC+
            Fq0X1Qo0D0EtDX+WJxkHp+r4yvheqrxEZF9TfZacb696LMmAxoyOOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieEpmYnEwTkxQdE4wdy9P
            Z0NvSHRhbVVhUHBud3VoZDQ1UnU4SG1GaDBJCldua0FZTFNjckk5Z0dBRmI2NVcy
            M0hycEdlM2FoRUpGaDRlZHhKQVBEOHcKLS0tIHkrVzQvL3RyNWZyUUlnUW5GeU12
            d2h3NTE3UVVFcXdFWFlyZFVpQkFCMzgKqZzpQJ58tSfDMVpkasdB47b6G7Td8Zre
            CKbPyZ6q55TRAdx8l/m2okD4upMYr2PIekn4lo/pPORyi/+HlsX8oQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbEF0TFFEQnZUa2hYNlIx
            ZGFkdklucEtnaGR6anhIZnhBN2E5UU9HaTAwCnNMcWJXZ3h4Q0VJOUVaOWY1L0RQ
            d3dDeFRVTXQvdWV6U2xEbEFjQnp0MDAKLS0tIDIwR1ZKL0NlQjVTRHpsbnlWajIv
            RUhidGNBUEp4MU9ZZ0d3ek1UTE9XTlkK1B0aRp5mkRkFBSdRbHyp+KfmowxP0Vbc
            CkUE/ePL2qHYLXQCQOMk/z2J1QUJmXlzYmpMYerRcAlGbYJ9zwR2DQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZXJHQjl3QW5VQ1pJbGgv
            eDdPWC9lWVN6eWJ2QzZlbS91aUNBb0kzUm00Cm1LVXhXbWt0S1ExWjdEZUZKVU5I
            Z0doUVVyYWRYUDRybEdmWTN6WU8rNWsKLS0tIE5XanZQbjdQd05NV083RVMrUE83
            RHJxcHZUNFZaTFMvd0x6RUR3NjIzVjAK3VWJoF4cYINSEYLUz+Ce5VsO/hVLRT/W
            Lt+kCyJhki4fy73THMHrIN/eDKPFQjLLfn6yVfSukdqBlQWhtw+gKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUEZENXFqajNXNXdGR09o
            VEhOMi9QVEJNV1JYNnBOVnpneVhjTUpnTWdRClp5aU5vRHoyZmhRelBranZXV2Vw
            emExUG1KZGhBWmhkQXdjd3J0QWZXTGMKLS0tIGZoVkRJSkJlWkJhR1cwSHdOSlBp
            WExDKy9EckpGR3FjWE50T1FpSUNLckUKGoHBmp1BPMxllQdBY4b9La9eXSfznEmt
            wmAigVrOKJB9z34eITaC4pH/FF56dtpZO9j2hSg+rQbZH32NhmpUbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T04:45:46Z"
    mac: ENC[AES256_GCM,data:6SZAy2xBYtaaJsjlWK/3psVRcrgyxJ8wYeBPusfKtNQkvDB6rG7CnKscSGiAeZym/mq9QKS16damSzQoEDLTyd3z/n46jAqombQ0V9z0ZueeJoEDDWc8dHkHxy34rE/2LNR4IoTOc6quUfLf8hNVEO2Uz0XsZoEsFXZqEVQMUpw=,iv:m7wSsmkia6wnS0nXYwYEBglvM2OPo7uclxEiEH5glnU=,tag:KKFteFnBQaaCkXwTeV4DHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
