apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dockerconfigjson-github-com
    namespace: ireland
spec:
    secretTemplates:
        - name: dockerconfigjson-github-com
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:VHSh/Sj+ez2m2owCAVDJ6HwZLuspuvu0h3bAGjBxzQYuMFJ1iPrMQUN2JoFEDwALEpOXd/5VdydKbWuPZmZsc7BJztW/wR3l5lBGaG03DCvtijISXBnH1Bgy68DXVVm6HjzigG+rOhL7,iv:iiov3IGlQB4Hl1lb64HzD/WqnXctmmA44Ng8MwlVHLM=,tag:YHmeeB6Goy8sQCW848r9yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK2FCR3loS3d0S0xxYjNo
            QW9peWpoSWpQNW5lSlhsUUNwTmF0ajU3YlhnCmpEaGtBa1FSZE9qOEZPTGgrS1lE
            VGRQOEtySWl3MFh6Qll0aWVITGJJa28KLS0tIGlyQ2JuOWx0RkYwaEs3L2tpQ0FO
            alpkUVd3SXBjeThvYkkrTE5ydGJFcmMKs+rxx+meLmsXmVBjJ7GR2qiyEdig+PJM
            XwxW37Y+e5VAgwvQTKV+DUS7DL2MeoUrjlbRoZZxsHcttm4Mf5JQ5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK2R1N1ZrQm5WYjlUejlB
            RUkwNFFiWHBobzlHZ1N1TkM2bUVIT0VkZGpnCkJyM0k3NXVHbmNVQ0MzYjU4azFi
            VTJtdXhNL3k3QVp6ejBQM3hDMk9sMUkKLS0tIElDczVZRG05MFVlYlNzL2p5SVg0
            NnRuM3JFdnFyMmlnVEhkTkRqNTdYd1UKMSKxvQzUqvosKEidtGogHPRZSBp8YmF8
            hQCI+nehIBNz4mn7TEKdKnJmYrZ0VtQxXv2c/O/3g1uTvN01A8291w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUnpjZXA2a2dvU3cvdFZj
            TXlMZ1RPbkRWQmh4OTRVYzRSZWRmOEhROFZNCkQ3WUlzdFo4cTh0ZDBmQmllbXg0
            MWkvTHUxbC9MZ21sSWErT2Nsb3hzeEkKLS0tIFN1ckw4ZTlvM21ucDFyRGtsakFo
            T3NBL1MrYXRwZDhxUUxoRUFvcm1mb0kKw5ULsNxJ3e/hdgu1lZHQwtbxxeZ9ABtD
            li0aubjNG1gQVlxjNFqQ6avqCGj2wrW4E/SFllXDbLlhSQwDaTjh/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeHVhWkowaWUvZDAzd0pB
            Z1FPMmg0VVZGejB6OGtqL292RE95WEJSUlhjCm9CbjR0WkVtbkNLallyV1hrdW5E
            M2hwQ3hvam5QVlJDeitaM0pmWUNaeVUKLS0tIEN1OUpTanNlbkVZNVFpN21vbjdo
            UVhacEZlMmVWK09ZZXVyWWlwaks5VGsKCqiFEbdfs4ySpSLfzejFuDZGDxe6W5XO
            HoYtqMnhRtw2ZEdKnmtaqBUBpwqZtARfveRFHl2I+/L0uV7ypDkw0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWW41a1NtUlIzYzhIanJs
            V01xYWh1cnVvUUJtUmhRUGhVOGRlZVU5S3dJCms5bjhKdDdoWUVPS3lkbDI4QWhM
            ZHVJd05EdXhMdktYMklPRnZrTnBzRXcKLS0tIFZyRWVLMW9oREZYVGxKOVNDWVk0
            N3pDWE1veFA3N1JVT0s3K29qMFFKazgKpIBJdPF+UQ0cpphPB0gCub4SUwL0WO+Y
            Mug4oNagmvCk/DyViVUIZhnL7sq/CMqicIJFDC5dBj/NGez6zGx/LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWWgyTk9xNEdJci8vQTFU
            Q2UyQlhsbGFDdlk3N3AyQlQyTjNkNkM5emlNCkVmRWQwRnkrak5Fb05rN3I5VXdw
            ZmR1cmtJVGdlSy93bUZoVnlkZVhzWFUKLS0tIGJqUDNjTi9lNnZpN3A2K21tOTBE
            Mk9aMzI5S1lZb3I4WDZmdlFjV1ZadWcKuzkqcxqevjOKl59mJmcbjo9khGhsPiFG
            4D0j1apdk1G1kJAsJy7Gtc2XiAqeMBVtwNLMUUWKogVvlRcyoAgA9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VnMxeFRCR0U1Mi8zUGhT
            alRlRXE4d2t0NEhWZXI2MHV3VDBRQVJWTFJvCjZBbk9tWlM4SlRnYWV6MjN4K1ll
            MFNFd0xSLzBobjNQNnRjaHlHeG9jaUEKLS0tIGRWRDVNN0hXZTduWUlGTk9mYURP
            SE5GSjIvdDZTSnFZK3JIeWdWVHcvMEEKPzAGOEwbS9CuSg4FPnp1r/qOMWtzGHkt
            s3BwAW17mY9FCeFrY7L7SEFbNVyXXAj7bB80c9lHFshT6WoF180FKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T06:24:59Z"
    mac: ENC[AES256_GCM,data:wy7RmcgBLomPw0AccNDIa4wl4DO/Ecu52tMPtjOZOt2/ZpJucS0piZKQ+ApFZudKr00jpfWoCMd7XPcMsEoesV4E+c3Ykz1CEOo5zI4ZfQkuCMZ6GaoUn6OnqiPxOk2ka+hEo3w/ew3ZcofuESxxM3+2wGlXOr16kRZGxrDBD30=,iv:cFiBK7xhfflUu86mqwiv8vsbyHywXNtD+SLbxr7TVVc=,tag:eidZxAJOuVwkT12R+3qR3g==,type:str]
    version: 3.13.1
