---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  BOOTSTRAP_CONFIG_FILE: "{{.ROOT_DIR}}/config.yaml"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
  SOPS_CONFIG_FILE: "{{.ROOT_DIR}}/.sops.yaml"
  # Binaries
  PYTHON_BIN: python3

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  PYTHONDONTWRITEBYTECODE: "1"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"

includes:
  argo: .taskfiles/argo
  kubernetes: .taskfiles/kubernetes
  sops: .taskfiles/sops
  talos: .taskfiles/talos
  workstation: .taskfiles/workstation

tasks:
  default: task --list
