---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.12
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    crds:
      enabled: true
    prometheus:
      namespace: monitoring
      serviceAccount: kube-prometheus-stack-prometheus
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      tolerations:
        - key: "arm"
          operator: "Exists"
    speaker:
      enabled: true
      logLevel: info
      frr:
        enabled: false
      tolerations:
        - key: "arm"
          operator: "Exists"
        - key: "armhf"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      image:
        pullPolicy: IfNotPresent
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
    - "${METALLB_LB_RANGE}"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement1
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
