apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: drift-app-secrets
    namespace: drift
spec:
    secretTemplates:
        - name: drift-app-secrets
          stringData:
            DRIFT_SECRET: ENC[AES256_GCM,data:AQLXTjSYoSgdneoSAvA9XVE8XRIYRUH8YGMe9U51QwETBJnD2eL9+am0agKg4rJ7L+9H+DRQMc85Iz20JC0CnQ==,iv:XreFkJ5MXHHLKkbgVY4KP12Mmb9QGUt+/7Af+PzOwQw=,tag:kDVUOUl8XQqGWnHsSio/Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NlpQd1ZtdEVXOWZMdE9U
            SFRqeTlCbUhMek1NTFBWR01DeVJVU2k1Z3hJCm1Hb3NVTVV6cTRzeG5IdXBDOFk4
            SmFscXJCSDB5SWRIYWZlUjNFY0VLVTQKLS0tIGJiWmN3djJHTWRIWXBWdmdqM1lS
            YnNCOFdUYmMxVS8xZllxTGowRkRCMWcK4JcX6UZgMuFkdi2p73U1rRL0yCjagcfF
            wQdKVYfjX6I0rPD1s8lHZMbuImWCNCSyPbv4FJWyyVd7IxkK86x5Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMWhBN0xiZytOeEVaTnhh
            VHI2YkpZemFIYTB3M2tYL01CN01zQ25oNlF3ClJ0Vnk3cmpJakRsWUVKVEQ5Nms1
            L3cydytYSnhTMXhZQnFsdzlvcmdJRkkKLS0tIDVmcWdrcXRsNkxNaVFlY3NFeFo5
            NG5haVNqdW83c1dSRUwxWDA0SHkxSDAK+U2So86sVt0hIYWWFXSt/lUlFQRP4Uhu
            +NbQs0w7qmOrWLRbO8u6evlzXKnub/0z6qQgAzlq7BqyCT62GjYcpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZUsxV1c5VUVsTGlKVTVM
            NGxkSmY1WUdKV2JFWnlhdThRZUtJRU8zeW5nClJmR1RRMTlSQy8yYWQxYk5GUjEz
            Q2xDQnByYk5SNExGbjlFd2FMVk83bXMKLS0tIHlPWWNXUS9TSTJvd3NMdlhOVEhS
            Wmk5REZIOEhjNFNOU1hYZzQyZ2N5T2sKYuVGl2g2fURDKPkxtT7aa7QLcBOhPHvh
            MD5kXzMN/Q6pv5pdfd/gqmAHOR7LkWDyd2UNVxGynqBKn0xeYVhwig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSGpYbjVMZ2tGN3k1Kzdm
            TGFqRjNra3hlRlVMc1VIYjFSalh0aExHd0dRCmlhMXJCMGRFQnp1T25UaWRzakoy
            ODFaNzFYZ0t0Z3hnc1R3ajIyWjAvdUUKLS0tIExzWHErRCtiZFlzRUJtVGpPcEpX
            QjVPTUJ5WDljTEhhL09zYjJnVElURzAKM4i309UIbbEihsLiYgSj8KpgkTuMZ6Vf
            VqXEZRq4Tj+VRPk/GYzObMBkEmJT4e53LNBRMThW0AvS9vUWpoyV4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncGpveGh4UGJxMG5IV2Na
            NjVJUWMxYmNScVNxdi9aUXFFeHJOcXdBSDF3ClljT0g2NjhJVGN1Sm0zb0tjMUps
            cVFOc0I3VkZWNllScHpxdVhjNEFVU00KLS0tIHIzSDhhUGJsclZwWHFZY25QSkg0
            angvWFNTSGZKUlB6WXl3THpDb1hCL0kKTYKGLaEPCXiwhJ+9P0b87mUeV5F9Bwfl
            VoApK2+moElxrsw6677RrU75OUGve3hy8n6H7ShOHzB9qDOUPxQrIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RzlrV2pPV0NyUHl2M0di
            bzJ0b05ZeTVSRTFEcGZUZzNQcXREeHNqcTNvClBOWTVtN3BUY1MzL0xtTFZlOU5j
            VTNTVlE3amF2Tk9WUDNXODdYeEZyOTgKLS0tIDJsNi9pekQxT2tuSWtadTh0anRs
            WTVYWUYxeENWSkUrUWgrQWpGaUxyODgKsPP216Qtn2zyNqUHgnc5+yae3YZDqSK0
            9lpcS14wo/D2LjC0BiRd8lhvOeyNd2QhV1IkelgYBHuUgytDc3oQfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WXVwNThYMnZYWk1XUG9l
            UGNOSEp0YTBqN08wbDlHczZWN3VYZy9YOUh3CkErL2pQQnIxbTBJOGtKZEw3SXpx
            ZEUvWmVaSXEzTGRVTXZXUFR2QXJHOEkKLS0tIDNLWW8zYkwvMVBJTElLQlc2VHRL
            ZDYrRW9PWkJncHE2WmVrMXBEcUxsSWsK4/kx6B5TdysWNqYwoKmBmb8rEpp3ma9c
            ugcQmQJydgeDiA+e7g2lbmo6bCeBoS37G/5TKrRrcktWIpiXJa0wcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T03:11:34Z"
    mac: ENC[AES256_GCM,data:OBcUqi+4Wd5VdjM5L4DZq0g4s7PLI/wmUFP55EzvVFHltRy/8K8mulhZzODj0g9Lptx55vjckWkuz6yKSqnI02KuqO3dPavhrwpEnJPxgpjgsQwK4yHzzrYGE5eA/0ai29iJYXS6pvhoetB2YPg8Q+0u0++gNnY57I6Ao7yRRNU=,iv:BsmmBivKjaPDSjj4BhHpQLkIHTuUO810zIUR7IC1l1A=,tag:bCa6rwx1ViVHTwDn6OYNsw==,type:str]
    version: 3.13.3
