apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dockerconfigjson-github-com
    namespace: drift
spec:
    secretTemplates:
        - name: dockerconfigjson-github-com
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:K5ioNfkcu3knPkxSi6Tqo4jycLoZ+T59+jRXJahMhxZ0a7JBAWXQUUAbTTM2rzADk6hOO6CHJLv2XAOuBE8MpOT7kVaHedOnu3x4EGwZV5JHBHtxzLwlJr/+u9dgeYnMsja5zOcl4Jxk,iv:C1BvAzwq4WiZN0OyoM/0PDVe5iSb4S8Suzrvkbw1VtA=,tag:EeQu4kjXANIVl8x7edFB8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWXRLYXBIbGlZTi9TSmp4
            MWduTWtGb3RFb3NVMzh0dG9WQXdVOE05TmtrCkJ1TTVrK09hVHd1a2lxU2ErU2k5
            NlA0MTNTKzVpdkdJR2JrYTlLSmt2SkUKLS0tIEdTRGQwbi9UbDZvOFMvNXBWSm9r
            RUdUd0tESmpidHhmYk16U09QQm1ETlEKKMSG+J2OAjbAWGUYET0Z+7qPhuFHk8s4
            KO78BLLdzwCHE154Ckbls0/KNfIwYTha8XR6o9WHKclCxl6iIGxkOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeVozNXBWMDdjSnhCWW9z
            RG5rTUdoYTFLQVRKVVhTOUFqQU5IMzlPRFU4CnBIazhSVnhQWUZiYWVtRFNaWTlk
            d01NT1Z4ZU5JZ3Jmc1dreUx5OTVhZ3cKLS0tIGk2eEluZGFibFo3c01vLzFQT2d5
            U1c4azA2L3c2NGkxc2JkL0pCSnZ4Y3cKOoKFGg3vI3LeWThgsQfFn3hJeTk2audl
            HzXchT4k2ze4AaM8/h3epf0RzaiQKGoDE6cByCbB4/vUPNkUIfH3cA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ2JKN3ZIb3hjNHdrQXFo
            R0tRTFkyOWlBeXpveG0rS2djM2N1K0daelNvCkNBN2RlMVFHZ1JGQWVBdnN5U1Zi
            TG02Rnp5YzNlRjZCZ0R6dy91bkZHSWMKLS0tIDFkWFNicy9JUFgzdS9PZmlNczhF
            L0NzVnZZOGVJOXhMOUxQQWhxK3N0QkEKg7nKNxZXrx/+CGvPlqRjRwPZfdNeFwOW
            pJt9HEPekJwHwYA7cJbIkDkH4ZSkSCVsIVDnyAvHmDV5nwRyi1Jvig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRy9aTU9oamRpQndKQXJG
            WjQyd3NKN2t4MnIyRFkwU0t4SXIvNjVTaUVNClpiTHVhVVdCZVBvSlNaVk1UeWVo
            YWhMajhsVkkreXhCNis2OWlraDE0ZHMKLS0tIFlVRC9DeEFUeGpyQVVuNi8zbVIw
            c0dKQWhzMS81QnlpajVLUmdOS1ZHd3cKHuIcrb7r2UR3ck2axHjeIFjAjL42XTlX
            oIZpjS5yVg2Mp7PRGdpVUfg2wdQKJUKJQn2FRzVZ6z5mfuci3PBNSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVE85ZXhwd0w5Mk9tTTVN
            VUNoQkF6OFdQVXgyeGQwMWprYUNTVGtYTXhJCm5yT3NPUjNmVXp2MXFQNHQ3VWVU
            MWhEaWhnajhmdjNUaGNmMUN1dnNBa1kKLS0tIDhWaW4rRXVkZEZ4TWJTK0p2RzNE
            c091SkdWK0NocC8vU3VpMlBTcE5oTEEKS9oR2pFFAnzWa51hnFo2ebWk2qQb33XN
            Xl2Ci57Cx8Jv1lkuPWYQwEBDydt2fCatp6a9kLwtEQRhgkMtuxtfoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOG9CL1FhbjdnR21YTEQ3
            SkhhY0EyTzNrYlN4clRxcWc0Mlo3N01VOTFZCkE5eFd4N1F3dWM1VXVtNm5vSkhB
            OHRRQkJ6RlBySzd3ckRXTUl2cGszS1UKLS0tIFhHUFg2UEJoR3REWHdCdFI3Q2NZ
            eVV5eGVYTEFvcTgyVlpqMDFMLzlweGMKIU19RlnwPlIOdUnhxGpU1acotT5XJflW
            0epdnlo7VexrG5HjND+KpZEvQsee04eA+gqrNa45wUD0fXTu7wi6hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbFdaWnNFblhxZW9Iem1S
            K01vdmVBcHZuTitUZlcyNzAxaGFXYnhZRTNnClFuVGR6V1FaMGd5Q0NUV3dJOGdP
            NWJvcGZwem94Y0FVTWQzbnZOWkxYNHcKLS0tIG03WGF3bmxqazhtSERKL0NHUjl6
            LzVJYjhRSWtMS29WTW9kOFB4VHRZTEEK25KPgl9mmIpyFOsHvebese+TuhnrkI6B
            MEOyxXrx1VRLzzP2+UcDkHFZBIFkHWV3yYauUjGL0g+2r/r80lKoyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T03:11:34Z"
    mac: ENC[AES256_GCM,data:Tk6ur7PhZN9WvcUXrIkmU0vHanOgE18Xvu7LGKG//GnTFgIoUfTWw7XguJXt0i1VrnOs3+oUYyMCcZZUfpYnq//tyyPIhKEjwVCEwl/FN+F3csZsVHY0Z8QQcTzirCzZz0TzlrRiuGW7OsNPTsnyj01Udmx8SJhX07XEpoXVTnE=,iv:J4L6NQoT4HtoHq7R937Q1KpCm8539MKOL83vyr2cAfU=,tag:LxPjfUAOfUrlRJI+hev6ZA==,type:str]
    version: 3.13.3
