---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  CLUSTER_SECRET_SOPS_FILE: "{{.KUBERNETES_DIR}}/argocd/vars/cluster-secrets.sops.yaml"
  CLUSTER_SETTINGS_FILE: "{{.KUBERNETES_DIR}}/argocd/vars/cluster-settings.yaml"

tasks:

  bootstrap:
    desc: Bootstrap ArgoCD and deploy root app-of-apps
    cmds:
      - kubectl apply --kubeconfig {{.KUBECONFIG_FILE}} --server-side --kustomize {{.KUBERNETES_DIR}}/bootstrap/argocd
      - echo "Waiting for ArgoCD to be ready..."
      - kubectl wait --kubeconfig {{.KUBECONFIG_FILE}} --for=condition=available --timeout=300s deployment/argocd-server -n argocd
      - echo "Deploying root app-of-apps..."
      - kubectl apply --kubeconfig {{.KUBECONFIG_FILE}} -f {{.KUBERNETES_DIR}}/argocd/root.yaml
      - echo "ArgoCD bootstrap complete! ArgoCD now manages itself."
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.KUBECONFIG_FILE}}
      - msg: Missing Sops Age key file
        sh: test -f {{.AGE_FILE}}
