---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.9.9
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
      interval: 1m
  values:
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    monitoring:
      enabled: true
    ingress:
      dashboard:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
        hosts:
          - host: "rook.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
