---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: 1.8.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
      interval: 1m
  values:
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    monitoring:
      enabled: true
    ingress:
      dashboard:
        host:
          name: "rook-ceph.${SECRET_DOMAIN}"
          path: "/"
