kind: Secret
ansible_user: ENC[AES256_GCM,data:EMbpsJBq,iv:QAgoptYVwpcDfMADIQDJ2m13XFhc8m2QEDyvD5aBzWQ=,tag:G+OJHUL3rzr0l+pmFdy5Tw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QYKW/2JxKSSe8g==,iv:1vZ92YzrdyDdCYxa6BUCMj/nkcpyfi7Q8G8BhBvY48Q=,tag:9rtHg8xVHO3p4R32Y6lwMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSalhIdTdsK2RlYi92RlF2
            ZHByRnk1Wi9hYjU3VkVMUVZKMjlLL1BtMTFzCkxjbmFtQjZRbmlHYk9WWnB4MkJl
            OXMyaHErVS9ETTdJZktSU0I2STJ1S2cKLS0tIEJlQ1ZtL3NmVThCOWhtSFZiaDlk
            akZ1K09TVHBwSEZlU05kdjNxS0JMVm8KdmHuETTYHortI2MTg7hKNutC+atPqqhd
            dI0Iolm/j1uI/cMd3oTzvyA+6AVsvhjChNi9vuP6f9uizNTZb9m1Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-23T04:09:04Z"
    mac: ENC[AES256_GCM,data:/L/siAoq4NlB/s9WO4ubwk/38866aNINZwyavbTL65a+XoBCABP6sTeH8UKTjwiBVGk99/dgPwFgEWuO+IcdKcNY4aHRC1EJU+/WoxjZ8EZTr1WUAErPG+Vxf7cmUh5L3AsEoWi9BxRqyHkTpwwlTQvkKzyDDPUrFlaEMwusyNg=,iv:2OJFigF0cxVlnaV2UmWYH9bABkWBKbqR5gJR30QL6MI=,tag:t2/7UQdV3cdfEBapXlK65Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
