apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: valheim-secrets
    namespace: valheim
spec:
    secretTemplates:
        - name: valheim-secrets
          stringData:
            SERVER_PASS: ENC[AES256_GCM,data:WDaueKnLHsESlZkCYZU=,iv:wbyQK/wJ9JE+HmXBC2N0h1EskpAwrGkRL8S3fmzpKiU=,tag:hbZTyRwuCtjRZxo7XEAorA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTVJIY1I5K0c4cFhjSXFn
            MnNHbGhrM0wvaUVOK3NNekx2YTd3TDRtTEdnCnl2dmlLeTFFRlZCQmp6d2Y5c0tt
            Ylo5WG0wd1F2U1hKRDJCdnU0cFlCWWMKLS0tIExxT056WjRWUXF0dEdoRkkyWmxM
            UU1IMmFkeHZLNEJaOEFpK1ZEb1BkZlUKA+s7rS5Rci2XwB1qkRrcdqhygplUrhxX
            V+Llu3yGPpVqThg9aKvdYwc45kKUUDT+XqXD5sf6aF5eQppbZpsbVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZEhtbmE2bXZJTGwzOFkr
            RUdpTTV3cENJWVc0MXYyd3dndHl2d0Zkc0M0Cjg2WXZxdGFCZUZ0Y0ZIY0FadmN0
            WWlYSEgxTUhTcy80bTZwVi9MdVVaVGsKLS0tIEVxajZRMlBQUHJ6NlZFcXZJdGtF
            TkRCcHlnSGhQOTJCbjRpYk1vMVpzcU0K4x9OZ0oDgxHtvx3tQ7lek5kvB++ltjfl
            6SynJ75IMB08tklbXMjWHpjcOHsdTcYU0JiqzkAF80iPwWsnkm3b4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWVhRRXRZUEoxRVB2Mm9n
            Ti96ZUdmQllQeWxxVEZCeHlDTVphMDRwYlZvCm9JVkVxazd6YVBnaWJuemNSMzhV
            V213b1ZpTC9GYjBVOGc5NW5aUC91MmsKLS0tIGhwbldXZ2hmV0lTZmRYZmVob0ZB
            OU1kMjJMOXlRZ1A2SFE1c3JrQ0JRb0EKU3XLpfKXJN0DBzcVYATnMADH9DC4KZuT
            xacOTrohnQoqU0QJ1O0e8MeVAUrjeMgj/c/HmxPBg9dLL35x9JelLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYXoyQlkyZ1EwVjN2Q1FY
            TnJ0MCsrQ1ZhaVdyTmR3Qzd6UUNNMFBmRGs0ClY5RlhzamVoMThnM3RDVmJFYkFk
            TEVRcENiT3I4bjRCMzRaOU1RbjU4K2cKLS0tIEsxZDB2TnIyRTFPWWoxT0Uzemtv
            OEl1TVhtTzNkU3UwOWgvUW5KQ2h3am8KYRFC9kHxpLCqlqpzYFYHlDcrDMfuSkOY
            B//7Yb//4NuGoivjgJM45TrsFME8RbpJk35uD0sXz3FfuePG9MZlUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YUhTWVNldWVXR0YvMERJ
            dHl6Y2ExTWN4WVFxVTk2RWVCRXNTNndXZUFBCm1hdXpxKzNXQTdsYWZ4amN0cEVF
            TkZtdGdyS1V3bU00R1hQMGdhU1FaeDQKLS0tIGxZVGZLTXFyYkF2Z3AwR25Pa3B1
            RFAvVkZzakpqOGh1aTJYR2t5UjR0VncKjVyz70oXmCkSg797mpJJEKSwGmCA1Z8q
            3NzlAEqxF84/I6i2uVdgNdKmSs6B+CS4YksNhtiunjnonN9VdJpPNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U0JkR040SjJGZjRtcmcr
            UTc2UVNnai81UHlKcHROTnFJU3Irazd1cGhFCmVuNXZuYWF0eVZ0dkJZUi9XTGJI
            MXZ4R1NySnZzMmZjd1dzNUV1RG45T3MKLS0tIFhjQW1LYWVMbE9SRjhRR3RFOUp2
            MHJLbk5xSUE2bXlaK1VJc1MySXhXQjgKSjUAJdyFFSqhRtYBsI5WFwLZLJX3mx/K
            sIiI5Th3EX2kUpUx9mvaDCRw8e7jO1TrhbkMxyeit/Kc/Oe3UBqtWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMUtHZUFEaFYyNndMQlNM
            K2dWdFhtVzQrVDhGZHpQalFseFJRaS9wdTA4CjhYZ1ZzV3BkbkZaNk9JUkIrTDhN
            Qy9NaWE0OEdPVUN3dFBZV1c0SGp0elEKLS0tIHNZZ0w0QkVPaU9ZQ2s5MmMybnpT
            UlBENUtuQysvUCtHcWE2eHJHaDFZZ2cKDCUlKb4iFnnCInqStUF5nKASHF/XVyRy
            MFxrXg/ZY4IcoxI17r4A5cPd9Tx3nMDKnzl9G6pPXxJXBS+5pf68qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T09:28:35Z"
    mac: ENC[AES256_GCM,data:fB1wDD6Ocp854/XtPzgeHVMZ+3xr+mWFjShOjZMse4g3azc9iqhhpxHEdpn1PhspdBOz9kZU13mXyY+E1XpfNFt5tGZ1jJJCCDzFczrh9TkU2SBPQHMnkAiPf/vJHbk8vuEjMmMGVkslftMqCgWEEzyz3hxjC6mzMYGlZI6GV14=,iv:78Wninsra0ZY/sJA9m+CDj7QiGiTaDgE2bKXTDtBCm0=,tag:XJELwABzttSHguRSOri/iQ==,type:str]
    version: 3.13.3
