apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dockerconfigjson-github-com
    namespace: home
spec:
    secretTemplates:
        - name: dockerconfigjson-github-com
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:znTVV9E2SDx6Klj4yw9fkz7N1e0lEqlBfcG0zebNwCiV971KLaOOQ2+71WiLWurbkZ4ELTHs0jz6ZOvvZosoFjL7Rr1meIaXFXmgrPjBQnImTmfmhy8cgY22nAER2oVTCRJJhhMFLln9,iv:wpuWrrttejQ9VbqeuA69PERaYXOMKfMlbEvnp4VQDuE=,tag:PCax89JkUfndfcr0+KwsgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMTlUbmR0TTBNWlI1TGlS
            RUJ6a3I0SkxWZEcwMXhzY2kxZDd1NXo4WWdBCm8wQ0xTc1QvRHFXOSsvNGFoZEdD
            K1FZYnFnVXIxSWxvTjd2aEtPbGp0S1UKLS0tIENtVGlyV1JKRlp6cmNKMVRiRy8y
            YjBadzZIcTlKT00zU2N3OGQyUkNQaVkKCR1791SyEn6qpVHlBwNIlLCBtWCMdH0d
            flT4+l6jbekhkgsEixwAlQe56WitylzsTJzSXImrRYNufd+jfNLKAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOVZ3SHo5YTBEUVovRDNK
            SEpIdnBxOWdmSmkyVzdMZUF2SjJrTlFkYzB3ClZ0MjJ4WVJyQ01rODJrRVY5YmxQ
            elBuNzZHVFBQQUxHbFo5VHo3VXl6Qm8KLS0tIENTa3dreVVQQ1gvSzFhNllWaW9w
            ZHZWNHdieWdaQktLanAycm14Y1ByNEkKeuoE5U8qNkzvAiN7ZrkPnl4buagje5il
            qfoA3NRqCMVsLX8skRGjim/KeokAyUmsHA7ciyEx5gTDRMlJfRZj+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK3F5dW1URjZ2TWxqdVdU
            eFgzMk0wb3JLd0hWQUFDYkVYWHNiNHd3cTBBCmFHVXY0OVpYTU5yQ3lZWVlBdSth
            K3NEbnhkR21sOEdsZWRmS1pjL3JpQlEKLS0tIGwwNXExeHAydVljL2l4N1JySmUx
            THlWeFoyTGVGdmcyTlZmZzlpNk1CUWsKf7OOWDIi0TUgQpSxD87v3TX/tgBPEk3Y
            9x24sF5bJF5kqHcGlIMO/SPQc3cDYblRFxOIsCRtn9gPfxSVn42MTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFalRHYXNUaDN3ZUM5OWR3
            RzIvTVFjZDBtd0NVc2lnMlJsbDdTM1JkcjMwCkxrTFAvcnI1SFNTeGlnaVMwNjBD
            cVlpSHJyc2xESmF6ZzgzYXVwck53a00KLS0tIDlRdjhMekp3QzhpOEZtUjFZNXZx
            VXVGR2ZvRWhkZzVQS0gvYjVZaURBWnMKgxqj54meCv7Dr3Lmyfjj0c8Nll3wrK7k
            q4LtcJCx1qoEhpeXuFKX8KA5bQl7AGdd/DUNH4e2sofewIBzyQz7Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUmRzTXYwc2ZSYXpGSnJW
            ZmsxSFk1bkVwVldrWXlJSmFUNjJzcStXWjNrCnNXNXdZMitjSVlTMDlaaDlXNHRM
            UXF2cmJOYXlORFBCR1F0OW90RXFyNkUKLS0tIFJOcXRYb0lvaWJsYlNJQm5IcGE5
            RnpIN3ZLQ1dQSEdiUDJnbTQzZW9rRm8KKwwE8WWFESqxopnU6hT7e+FleveMOJWt
            K/CeWCu3fN4aw0TsHHhZCsZd79fFlMuPwLk6fMa1AJ4sKgmKBGx/Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlK0hObEI4MXBjNTgvbjBh
            ekdyK3R0Mk1vd0NrWVpqakZVbnVwMkp6RG5VCmxiMHZ1b1JGSDJsNEFqTm9hdlRW
            UjBqVmNiVStoamFyd2grWGZRNWpVc0kKLS0tIG8yakRJa1d2MERPRDNBSzBwVWFq
            NlRtZkhqYkMrMFpkT09nZy9LNTdJZmMK/x67VDCud5EK0IBcmlfLWi4sh1LkNTGd
            k5e7MNy0xekiwyfYWOtsx4+ZNd/sn00zjTz/CTgbV5/8hQ4Z0i1tew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYU45eUMxV29EL1lvT1NG
            MkxOa0JFVEZqL3NzU1dJeHJnZmREUmVhMFhNClhFTk0xZnVNcktmS1pGUUI1a1Fm
            cVVibkdwbktRcDd5TXBWSUMxdWQyQWcKLS0tIDdFTEgrcmEweTU0R0RuR1VGbXJV
            NWN1T0FiWjdLNmo1UitoZjZOd3VzTUkK4ozPaWDN4VUt0sYSoxC6MuKPEruYBX+O
            kdGpiyrbugi8v5Tvc8PDmWDu1gcj1/mVJeetE0iFZPAm0ShPIHGJig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T08:23:40Z"
    mac: ENC[AES256_GCM,data:IMlj6nhAjKGVg9GRVbkxGB7lYduH1T0KSIJ61kgO4iGJ5BmkuXCZ1AtGiCZZPph5OdAE0ChavvWB1yIBvRHSbxA9kryrUBGe2n4tUtzGNSz3d4BLq1xGASSZBRS8dtade899HJzRuAKKMM/fxXfcJs9Ub88sPwkBA3cfwUmJo0c=,iv:7XYRhp+3M4OaeRWOiFxWlvQ0WZ2us82NmPtENrKkKI8=,tag:qW368S8L0zNxfQN1GCKE1g==,type:str]
    version: 3.13.1
