---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 1m
  install:
    crds: Create
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    grafana:
      plugins: "grafana-piechart-panel"
      adminPassword: "${GRAFANA_DASHBOARD_PASSWORD}"
      defaultDashboardsTimezone: browser
      sidecar:
        dashboards:
          searchNamespace: ALL
      serviceMonitor:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Grafana"
          hajimari.io/icon: "chart-areaspline"
        path: /
        hosts:
          - "grafana.${SECRET_DOMAIN}"
    prometheus:
      prometheusSpec:
        retentionSize: "40GiB"
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: ceph-filesystem
              resources:
                requests:
                  storage: 50Gi
        podMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        ruleNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        ruleSelector: {}
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Alertmanager"
          hajimari.io/icon: "chart-areaspline"
        hosts:
          - "alerts.${SECRET_DOMAIN}"
