---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.9.1
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
  values:
    replicaCount: 2
    maxSurge: 1
    maxUnavailable: 1
    serviceWeb:
      loadBalancerIP: "${METALLB_DNS_SERVER_ADDR}"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: "${METALLB_DNS_SERVER_ADDR}"
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    antiaff:
      enabled: true
      avoidRelease: pihole
      strict: true
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        hajimari.io/appName: "pihole"
        hajimari.io/enable: "true"
        hajimari.io/icon: "pi-hole"
      path: /
      hosts:
        - "pihole.${SECRET_DOMAIN}"
    dnsmasq:
      customDnsEntries:
        - "address=/grafana.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
        - "address=/hajimari.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
        - "address=/pihole.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
        - "address=/rook.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
        - "address=/traefik.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
        - "address=/paul.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
        - "address=/gibson.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
        - "address=/bonjour.${SECRET_DOMAIN}/${METALLB_TRAEFIK_ADDR}"
    whitelist:
      - "${SECRET_DOMAIN}"
      - "grafana.${SECRET_DOMAIN}"
      - "hajimari.${SECRET_DOMAIN}"
      - "pihole.${SECRET_DOMAIN}"
      - "rook.${SECRET_DOMAIN}"
      - "traefik.${SECRET_DOMAIN}"
      - "paul.${SECRET_DOMAIN}"
      - "gibson.${SECRET_DOMAIN}"
      - "bonjour.${SECRET_DOMAIN}"
    podAnnotations:
      prometheus.io/port: "9617"
      prometheus.io/scrape: "true"
    monitoring:
      sidecar:
        enabled: true
        port: 9617
    adminPassword: "${PIHOLE_DASHBOARD_PASSWORD}"
    adlists:
      - "https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts"
      - "https://v.firebog.net/hosts/static/w3kbl.txt"
      - "https://adaway.org/hosts.txt"
      - "https://v.firebog.net/hosts/AdguardDNS.txt"
      - "https://v.firebog.net/hosts/Admiral.txt"
      - "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt"
      - "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt"
      - "https://v.firebog.net/hosts/Easylist.txt"
      - "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts"
      - "https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts"
      - "https://v.firebog.net/hosts/Easyprivacy.txt"
      - "https://v.firebog.net/hosts/Prigent-Ads.txt"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts"
      - "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt"
      - "https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt"
      - "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt"
      - "https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt"
      - "https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt"
      - "https://v.firebog.net/hosts/Prigent-Crypto.txt"
      - "https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt"
      - "https://phishing.army/download/phishing_army_blocklist_extended.txt"
      - "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt"
      - "https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt"
      - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts"
      - "https://urlhaus.abuse.ch/downloads/hostfile/"
      - "https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser"
