apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-db-user
    namespace: postgres
spec:
    secretTemplates:
        - name: paperless-db-user
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:lPfmFRkPVN1V,iv:ekdXpjuC1f9Z2izjnah+0F9PUuAJ2Mz2ip+3poFhzao=,tag:gvMNjWXhrJ3k0t8+v53YLg==,type:str]
            password: ENC[AES256_GCM,data:rsGLtWPeovCzluoimMzmhp0Hl6LF1TeNbHp/yJvmQws=,iv:0hiTELijldheFanGJaiExgQavku3Illw1U4/hGI/AH4=,tag:I4AEGa/tx6fUF3IgtODwYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZzFEL2NJMFdsbW5iclZZ
            QmFXenNYeUg2V3pIVTA0aGYzT0EwNi95UHlNCkJNS0FJZ3ltMzg5RVV2VWJzcStI
            ZHM0YXNPRzBETUtDSE1tVWp0c1BmWncKLS0tIEoyNTZuRzNYL1Y0ZHV5eWozdFJ1
            a1pudkNKRnc5N0dicFJSOFRZaFk4NGcK7UOCWsc8tlg93wPvUlHY+X+8ObzqV8Q7
            EdnuHSRl/ACzWf3FUtAEBtTUxetyr1+r8CAeYPVaCNPjiAVjcFp9bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRWsyUi9TdERLaW9xWGhm
            WEtqK0dpVWk3bkFYUlZLYk01YWxJdWJIU1UwCmxDWFcyeGo5REpycU51UmNtUG0r
            UjNCRGF5ZkRZOUZaL2tvbE9ncENoVlkKLS0tIGFsbUVHMU5uc3BXTFRtOHBMdFNP
            QURiS1kxS1cvYXZCMjNVRFpLTWRXczgKhwuzjGCeH8W+GPHUo/2WywqDTpyIawe9
            vVBmssALJgkacgXU5z4sTtkXdnA4uUUJRU0UXYnM68gUftkChLMiaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QXVQWjdxMmZGbm5RQWNh
            UHE1M2FiL2lIeWFNanhaZ0dxeTdtKzk1cVNBCkFiUFp0dlZQdlhkU3dSaWI3S1pK
            bVZZNHV5OXk3cjk2S1dPRDd4L1NHRDQKLS0tIEd3UzZmUVhFZWNSV2RZNnIzMElB
            bldQRDNTU0xTVzBJb3ZseWV4RnMrQnMKjOob1+ZZuGMjrZqF1mImopti1y0Hd/3p
            qnfnmMMic4Sd3dJ1Zs7xgWfgvY8Eg7+tN3ELjknm1C/3XlrypcXQ8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNEFOTUZETVJkNXpLUHF4
            eFAyNkliVkUwOHN3aCtGRDFvREdXV0pzTlFNClRZK2Z5d1RGN2hCenhZVVdzL0RT
            UlM5SHB5UWhrbE5iUy9uamVyVExNeTQKLS0tIFovUG5lNHExSzg3c0hGU1Q1NWNq
            Y1R1NW9YMWZSVUJGYUd5R1cyYURzOEEKqBai33Yq8k9JcY0bObIGZnbmbTvmPcEB
            HfJotwANs6G+3WhmFGnF5RK50FN9OBKGBaOJSQyWjhbH0w89fhcpkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbzQxY1VBK2hRWDh3MVE5
            NEpHUzRYM3VMeGk1ZW5TLzIvYVNtdTlnMG1ZCjJuYVhJeDZYTlBCS0UyR2t6eldQ
            VktVeisyM3crdFhjQkZRd0I0a0hVYVkKLS0tIHNJcGMxWjIzZDdoUDltY2JiWG5U
            a09MSFdpVmtFeGFrcUZvbWI5M2M3SUUKnqKu72csyeLRWI2Nv2PX5TzMoV5hoT90
            7UsPW99wQZjtg5ut2FvnMavJAaB29arv+JcFr5Q8lNiGRyq3CM0XHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSzlFTVdPcmxlUUx5eEkx
            RmFQbENYbXI3RnpwZ08rZDFxVEZKREZrTzAwCjFlVkNrSXdjdmx1OEdhT0tCL2lD
            bERKbisxVkVvYzV4SGdrdk93c2xPRW8KLS0tIHNPdGU3QnplUXY5L3BScEYyVGFm
            VXRsT083R2laRU1xTzRLbHdGYWcvM0EKHujD0wuXOVNGM70fjOOrR8fPV0YXZOzW
            LuS4Ywg4mQF+JU97l6kQCCyoJon42YohOdaZ+N07xQ47hKFJ5j8D/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOVBveEVvZUI1dWszREs5
            dXdZdm1meVRuWlNIdXJVVWIzMXptR1Vua3lrCnFDTUhaQlp4TG9LeGI4Y2x2TGY3
            TnhFc25nZ3lsQmNzL0s4a3lYL1NnRVUKLS0tIEdEWWhYTE1taHdhTzVOcUozSU0v
            S2hYREV0aVhtMUNuTzBOaFZCdEdIYXcKMhpFIHF54x1o9qU1JhypMe7B0Q5Rpd2Y
            95Rfq5DLQBZVG7H/Cn5vtYx+8yS5majCCUbzgHoDqjyRngw6J/JL4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T21:22:22Z"
    mac: ENC[AES256_GCM,data:sKl7bhBjS3bideTBgDRup4VDXMBM54Loq5TRP+s6ZXHK9IjsQPLVjknVgeJpVKAvYtUMg30hsun2XRn1by7XBw1p5QfeggWfkWR7efiz4U1uKIG8Esh7oIcHVbEIxEJtRf9SuwGpk6BtySS2HMMSWeY4/L776OsJLcg9UWBt0ow=,iv:8mlbItkYPPoLfn8Ax/ywwpKJE+l5KJ1XzMRgBf5mrR0=,tag:I1zLwikKvtd5D5NlVl4ymw==,type:str]
    version: 3.13.3
