apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tidewood-db-user
    namespace: postgres
spec:
    secretTemplates:
        - name: tidewood-db-user
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:cM2NWh0uIiI=,iv:FPkmM8/S4O3Hp5XVVWNTiT3ZCcLQgZiBIfynBpgAjdc=,tag:1xG2NTfoGicjbgMWH4mrxQ==,type:str]
            password: ENC[AES256_GCM,data:JaEgVY4DLBlS2cSH+ZEv8a+tfOE1c1yFLBy3alH9tUSCFTvcy7x7Mg==,iv:cFt4C8Ue/tPzX/pHDpBgvyp/WITn++yUFGbXazZzLEs=,tag:SzlL10BW7vbQ18RzbowuEg==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcG5UdFd5bFdEaEJEekxm
            M2Vmb21EM3VCTVA3SG0yRm9oWWVBMS9FaERRCnpsZzE4R1RkVk5ZZS8rRUg4c1ha
            aEZ0M0FYeHROS24vQzE2eUUyTXJPdEkKLS0tIDlIcnZtUkhyUWxaNzVsOG1YaTNC
            bzBUbGhpVUhTc05tL1hxZi9DbGNhWUEKj/ZKU0SZ1WNn/TmimVa7e/x39ze1CiyA
            2wLJRUQTBTavt6z1wQ0lu7oSsFeBm4rz3QKx7a9CKiU06eNDUsVtfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUFR4aURBRWlUdVZNMCti
            TWNDMzVTZ0h3Yy9VdjZUVXFlR1BoWlY0YzNzCjU0WitpUzlJVVBNYlBMODVzZWtz
            SHdHeWZjKzdyRDRpZVNHZkJ4dmJRa2cKLS0tIEF2eHJ2QURGSmFiUWlQMkdiOE4x
            YmlMbnc3TkNIallpNzU1NXBUeEtlM2MKSy7bIGElPhf08ueY0QVwJ5wbY+0wB/DM
            EltEdehEHYZbOu7YpMOFmANSokazKqX7tOhEXMzmzifYrb/Z1zbBYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Znpwbk91ZmNtUkNheWo1
            eWVINGFCWlVSR3c4cHE2QmJvV1BrQURwMmhRClRwRFczMG84Ym1OcVo2VHpUTVJG
            a2s5eFUvM0xMZmtMdDNId3pXUEgzSWMKLS0tIDJnTCtRcXVzVVlMd3Y2UWNOYzc2
            dDRBWGRrQldLZjBsZTJ2aXdrU2xqb1UKHJ/sXHgvVRhpOgQWT6bp0VPXOps1abqd
            fLj8Gqf6jAEdqmZgKoSPfMB5PIZxaPIl3UZnMtR13bLgs9YYCSfufA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMjBRVXVrMXNLRkRvRGNs
            NGZVU3gvdHY1OGlmUkNzQWVRL1YzM2dTZEhnCjR3TEsvT0huemlLdmJ0NmlqcXZO
            ckY4Um5wdGZBNzZHV1piRzVGbDRlekEKLS0tIDR3ZFBlN1orRytYTFpLNG1tdWZP
            d2FSWnNsdFl6VUJiV3ovSGJRK0RXSkkKHTXGBsRphB5DqkGXEw7U+mDyCQWQNx2w
            EwbeWkKK35HTx8TCRs0LJ5vhyaM1tEkHQzU12IKif/JX0OMjQg3xqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NWJ5RGdHbTdsRDQ5Z2tH
            SHYrd2pYOUIzN25ZN2poeXdZZm9BVjQyaEdNCmFrZDhwUFBEMlZVRHhTenIyUFly
            UkgxMXJLZWJCMlVDVkRkUEEycWVSM3cKLS0tIFRlREtmSGdkOFFkU3pVNDc0Y2tR
            U3M3UzBEbnNDbElKZ2ZhQ1pBL0t4UkUKZYn/XaIwG+nmeSaY93Bk+FKKGwBvxAv7
            45eo/i+kLJ+vbzjk+dzUWgBNSWzZ75afndcHZed183I2FKJUiKZn+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUjNvVGhMTmppTW1JbkdJ
            YUM5R20zODdYWEtYbTVnMlFXc0l5Y0dVc3pzCnRlZ2lqY0VtRHpWemVwaWc5a3Mx
            djdCamhxQlIwdngxOVlJSStWNHFSMk0KLS0tIGU3ZHQ2SlVqSzIyM2VVbUtxSFpX
            V2xQcjVqZVVGWitrMmFVZVo5aThSalkKzokTtGVeWF0Jgyk7x0u5Xv3hEGh8FA1a
            pdFNtHn6xpibEr3mK6YKR/vYqaDxku6X64makq2l5bmpuXEYjwPq6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NFlDaEtkQkYvZENHUDZl
            aTUwOHRVQ0dkdlRCTzdFTGx6UVRuMTBEUTNzCmg5R2tQSGM3c3ZYbmY1MThvdG1s
            MUhGYkM4dVZkSmZmUm56Tk84eFozczQKLS0tIExQUVJjbjRHU3YvdDhxQklCVHM5
            OG5rOFJudlVESUZMeGpXMVZOUmFlZmMKiVV1Af9crxGD2Ebtep4k+WIPWAHnIFcC
            wGCRX0l/ZLciJdMNGsUC/Qtk9p7WVNvZx5UajvXt8dZXQFSPMkdeNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:22:09Z"
    mac: ENC[AES256_GCM,data:hBrMINkXv4W8J8S/NsdCpG3vDV5nqmJ8Ywd80E2fKykrpzH6dVkkeXzkey8VFGHVm7pANBLoxE34i9D9OSTI+iadeYCAIXbZEkQ5lW3iT+1z8bpRBU6sypJXaL5Jc24RWalNXWmdmwgV0AmEJH1CipNTz0TGMxywC0gS5F02f1o=,iv:VMZpQPqf3GPBqrQPdemoeU8ynmVNn/tTIfCu+cn8j4w=,tag:aMrLstMTtZyflpec25jDZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
