---
- name: Enable cgroups
  lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '(?=.*root)(?!.*cgroup_memory=1 cgroup_enable=memory)(.+)'
    backrefs: yes
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
