---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 16.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    image:
      name: ghcr.io/k8s-at-home/traefik
    deployment:
      kind: Deployment
      replicas: 3
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${METALLB_TRAEFIK_ADDR}"
        externalTrafficPolicy: Local
    logs:
      general:
        format: common
        level: INFO
      access:
        enabled: true
        format: common
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${METALLB_TRAEFIK_ADDR}"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      traefik:
        expose: true
      web:
        expose: true
      websecure:
        tls:
          enabled: false
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
    affinity: {}
      ## This example pod anti-affinity forces the scheduler to put traefik pods
      ## on nodes where no other traefik pods are scheduled.
      #podAntiAffinity:
        #requiredDuringSchedulingIgnoredDuringExecution:
          #- labelSelector:
            #matchExpressions:
              #- key: app.kubernetes.io/name
                #operator: In
                #values:
                  #- 'traefik'
            #topologyKey: kubernetes.io/hostname
