apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d0JzOWFVbXRFOGtXdCti
            MDNRZGZEajFJRGdKLzZIK2F5Y0tSb3luQ0hjCjBWNDlOODJVNVhqYUNDSFliUWV0
            bkRUWmxTdFAwOWpFdVBTbDI1VWhsT2sKLS0tIGNvaDN4cmhJOVloMHBnQkFXRTZw
            UGwvNDBOTWNlaW0vOThrelgzdE9wVVUKKNanAVd+8oqjQTQSjWTGnrnz8uj4SNRu
            KtIcsw+VXsLTya44qKz3cTvi/S5phAFNDU1Kd/XQupsIPc1FBq1W4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T07:06:26Z"
    mac: ENC[AES256_GCM,data:Pzig5LCekDQUFDVjWjrMvXfgFgTM1cUXUpWN0u36aSeUc5IR/uMDR2XQ9ruJGoBy6hm+tSyBqZo1n1Hsr+rMY/GDm3yrcRZrNaomQKgBTrG9UiC/eRJuThd/RNqz83SlcrG0LDXAeYwqBZQRTlVNb0k13T1sf0gvhS9bwhdbrvc=,iv:qsjK9UXOJtcl5q1uIyhaAUPEU+inJS6i3cKhKD0binM=,tag:DYHlcjMHvdauK20GUjXBvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
