---
kind: Service
apiVersion: v1
metadata:
  name: gibson-webgl-service
  namespace: gibson
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gibson.home.lab
spec:
  type: LoadBalancer
  selector:
    app: gibson-webgl
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
