apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - path: kubernetes/argo/cluster-resources/external-dns
      repoURL: https://github.com/paulkiernan/homelab
      targetRevision: HEAD
    - repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 8.7.11
      chart: external-dns
      helm:
        valuesObject:
          provider: webhook
          extraArgs:
            webhook-provider-url: http://localhost:8888
          sidecars:
            - name: adguard-webhook
              image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.1
              ports:
                - containerPort: 8888
                  name: http
                - containerPort: 8080
                  name: healthz
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 5
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 5
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: ADGUARD_URL
                  valueFrom:
                    secretKeyRef:
                      name: adguard-config
                      key: url
                - name: ADGUARD_USER
                  valueFrom:
                    secretKeyRef:
                      name: adguard-config
                      key: user
                - name: ADGUARD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: adguard-config
                      key: password
                - name: DRY_RUN
                  value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
