apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - path: kubernetes/argo/cluster-resources/grafana-cloud
      repoURL: https://github.com/paulkiernan/homelab
      targetRevision: HEAD
    - chart: prometheus-operator-crds
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 19.1.0
    - chart: k8s-monitoring
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.0.23
      helm:
        valuesObject:
          cluster:
            name: paulynomial
          destinations:
            - name: grafana-cloud-metrics
              type: prometheus
              url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
              auth:
                type: basic
                usernameKey: "prom-username"
                passwordKey: "access-token"
              secret:
                create: false
                name: grafana-cloud
                namespace: monitoring
            - name: grafana-cloud-logs
              type: loki
              url: https://logs-prod-021.grafana.net/loki/api/v1/push
              auth:
                type: basic
                usernameKey: "loki-username"
                passwordKey: "access-token"
              secret:
                create: false
                name: grafana-cloud
                namespace: monitoring
            - name: grafana-cloud-traces
              type: otlp
              url: https://tempo-prod-15-prod-us-west-0.grafana.net:443
              protocol: grpc
              auth:
                type: basic
                usernameKey: "otlp-username"
                passwordKey: "access-token"
              secret:
                create: false
                name: grafana-cloud
                namespace: monitoring
              metrics:
                enabled: false
              logs:
                enabled: false
              traces:
                enabled: true
          clusterMetrics:
            enabled: true
            opencost:
              enabled: true
              metricsSource: grafana-cloud-metrics
              opencost:
                exporter:
                  defaultClusterId: paulynomial
                prometheus:
                  existingSecretName: grafana-cloud
                  username_key: "prom-username"
                  password_key: "access-token"
                  external:
                    url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
            kepler:
              enabled: true
          prometheusOperatorObjects:
            enabled: true
          clusterEvents:
            enabled: true
          podLogs:
            enabled: true
          applicationObservability:
            enabled: true
            receivers:
              otlp:
                grpc:
                  enabled: true
                  port: 4317
                http:
                  enabled: true
                  port: 4318
              zipkin:
                enabled: true
                port: 9411
          alloy-metrics:
            enabled: true
            alloy:
              extraEnv:
                - name: CLUSTER_NAME
                  value: paulynomial
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: grafana-cloud
                      key: access-token
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-008.grafana.net
              auth:
                type: basic
                username: "1223707"
                password: "access-token"
              secret:
                create: false
                name: grafana-cloud
                namespace: monitoring
          alloy-singleton:
            enabled: true
            alloy:
              extraEnv:
                - name: CLUSTER_NAME
                  value: paulynomial
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: grafana-cloud
                      key: access-token
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-008.grafana.net
              auth:
                type: basic
                username: "1223707"
                password: "access-token"
              secret:
                create: false
                name: grafana-cloud
                namespace: monitoring
          alloy-logs:
            enabled: true
            alloy:
              extraEnv:
                - name: CLUSTER_NAME
                  value: paulynomial
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: grafana-cloud
                      key: access-token
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-008.grafana.net
              auth:
                type: basic
                username: "1223707"
                password: "access-token"
              secret:
                create: false
                name: grafana-cloud
                namespace: monitoring
          alloy-receiver:
            enabled: true
            alloy:
              extraPorts:
                - name: otlp-grpc
                  port: 4317
                  targetPort: 4317
                  protocol: TCP
                - name: otlp-http
                  port: 4318
                  targetPort: 4318
                  protocol: TCP
                - name: zipkin
                  port: 9411
                  targetPort: 9411
                  protocol: TCP
              extraEnv:
                - name: CLUSTER_NAME
                  value: paulynomial
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: grafana-cloud
                      key: access-token
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
              extraService:
                enabled: true
                # -- If set, the full name of the extra service to create. This will result in the format `<fullname>`.
                # @section -- Collectors - Alloy Receiver
                fullName: "alloy-receiver"
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-008.grafana.net
              auth:
                type: basic
                usernameKey: "fleet-mgmt-username"
                passwordKey: "access-token"
              secret:
                create: false
                name: grafana-cloud
                namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

