apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 35.0.0
    chart: traefik
    helm:
      valuesObject:
        deployment:
          enabled: true
          kind: Deployment
          replicas: 2
        globalArguments:
          - "--global.checknewversion=false"
          - "--global.sendanonymoususage=false"
        ports:
          web:
            port: 8000
            expose:
              default: true
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 8443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
        service:
          enabled: true
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
