#!/usr/bin/env python3
"""Render this app's Grafana provisioning assets from the canonical source repo.

The canonical definitions stay owned by paulkiernan/diff-logic-cells:

  deploy/grafana/dashboards/*.json        every dashboard, no exceptions
  deploy/grafana/alerts/*.json.tmpl       every rule-group template, no exceptions

This script only adapts them to the local Grafana (which provisions from files
instead of the Grafana Cloud HTTP API), so nothing here may invent rules or
panels:

  dashboards  ${DS_PROMETHEUS} -> the local datasource UID market-prometheus,
              and the export-only __inputs/__requires blocks are dropped (file
              provisioning has no import dialog to answer them).
  alerts      __DATASOURCE_UID__ -> market-prometheus, the group's folderUid is
              replaced by the local folder title (file provisioning takes a
              folder title and creates it), and the per-site absence rule is
              expanded once per expected site, exactly like
              deploy/grafana/apply-market-recorder-alerts.py does for Grafana
              Cloud. Every template becomes one rule group; group names and rule
              uids must stay unique across templates (Grafana keys groups by
              folder+name and rules by uid, so a collision would silently
              overwrite rules), and the generator refuses to emit a file that
              would collide.

Expected sites come from the measurement ConfigMap in this repository
(kubernetes/argocd/apps/workloads/market-measurement/manifests/configmap.yaml,
key `sites`), so the two backends can never disagree about which capture hosts
must be reporting.

Outputs (all generated, all committed; run with --check to detect drift):

  manifests/assets/dashboards/<name>.json   import-ready dashboard JSON
  manifests/grafana-dashboards-configmap.yaml
  manifests/grafana-alerting-configmap.yaml

The ConfigMaps are the kustomize inputs referenced by manifests/kustomization.yaml
and by the Grafana helm values in application.yaml. There is no other generator
and no task in .taskfiles/ owns these files.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
MANIFESTS = HERE / "manifests"
ASSET_DASHBOARDS = MANIFESTS / "assets" / "dashboards"
MEASUREMENT_CONFIGMAP = (
    HERE.parents[1] / "workloads" / "market-measurement" / "manifests" / "configmap.yaml"
)

DEFAULT_SOURCE = Path(
    os.environ.get("MSR_SOURCE_DIR", Path.home() / "workspace/github.com/paulkiernan/diff-logic-cells")
)

# The Grafana datasource that points at the in-cluster Prometheus. Same UID in
# the datasource provisioning values (application.yaml) and in the alert rules;
# dashboards reach it through the ${DS_PROMETHEUS} substitution below.
DATASOURCE_UID = "market-prometheus"

# Grafana's hard limit on alert rule UIDs (pkg/services/ngalert validation).
GRAFANA_UID_MAX = 40

# Folder title for dashboards and alert rules. File provisioning creates it.
FOLDER_TITLE = "Market measurement"

# ConfigMap names referenced by the Grafana helm values. The alert ConfigMap
# must carry the chart's alerts-sidecar label so Grafana reloads rules without
# a pod restart.
DASHBOARDS_CONFIGMAP = "local-monitoring-grafana-dashboards"
ALERTING_CONFIGMAP = "local-monitoring-grafana-alerting"
ALERTS_SIDECAR_LABEL = "grafana_alert"

UNRESOLVED = re.compile(r"__[A-Z_]+__")
DS_TOKEN = re.compile(r"\$\{DS_[A-Za-z0-9_]+\}")
GENERATED_HEADER = (
    "# Generated by generate-assets.py from deploy/grafana in "
    "paulkiernan/diff-logic-cells — do not edit by hand.\n"
)


def die(message: str) -> "None":
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def expected_sites(path: Path) -> list[str]:
    configmap = yaml.safe_load(path.read_text(encoding="utf-8"))
    raw = (configmap.get("data") or {}).get("sites", "")
    sites = raw.split()
    if not sites:
        die(f"{path} has no `sites` entry in data")
    return sites


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def yaml_block(obj: object) -> str:
    """Deterministic YAML for embedding as a ConfigMap block scalar."""
    return yaml.safe_dump(obj, sort_keys=False, default_flow_style=False, width=4096, allow_unicode=True)


def substitute(value: object, mapping: dict[str, str]) -> object:
    if isinstance(value, str):
        for token, replacement in mapping.items():
            value = value.replace(token, replacement)
        return value
    if isinstance(value, list):
        return [substitute(item, mapping) for item in value]
    if isinstance(value, dict):
        return {key: substitute(item, mapping) for key, item in value.items()}
    return value


def render_dashboard(name: str, raw: str) -> str:
    dashboard = json.loads(raw)
    if not isinstance(dashboard, dict) or not dashboard.get("uid") or not dashboard.get("title"):
        die(f"dashboard {name} must be a JSON object with uid and title")

    inputs = dashboard.pop("__inputs", [])
    dashboard.pop("__requires", None)
    placeholders: dict[str, str] = {}
    for entry in inputs:
        if not isinstance(entry, dict) or not entry.get("name"):
            die(f"dashboard {name} has a malformed __inputs entry")
        if entry.get("type") != "datasource" or entry.get("pluginId") != "prometheus":
            die(
                f"dashboard {name} needs datasource input {entry['name']!r} of type "
                f"{entry.get('pluginId')!r}; this Grafana only provisions the Prometheus "
                f"datasource {DATASOURCE_UID!r}"
            )
        placeholders[f"${{{entry['name']}}}"] = DATASOURCE_UID
    rendered = substitute(dashboard, placeholders)
    text = json.dumps(rendered, indent=2, ensure_ascii=False) + "\n"

    tokens = sorted(set(DS_TOKEN.findall(text)))
    if tokens:
        die(f"dashboard {name} still references {', '.join(tokens)} after substitution")
    leftovers = sorted(set(UNRESOLVED.findall(text)))
    if leftovers:
        die(f"dashboard {name} still contains {', '.join(leftovers)}")
    return text


def render_alerts(template: Path, sites: list[str]) -> dict:
    text = template.read_text(encoding="utf-8")
    text = text.replace("__DATASOURCE_UID__", DATASOURCE_UID)
    group = json.loads(text)
    group["title"] = group.get("title") or template.name
    group.pop("folderUid", None)
    rules = group.get("rules")
    if not rules:
        die(f"{template} contains no rules")

    # One absence rule per expected site. The template ships one rule carrying
    # __EXPECTED_SITE__; losing it would silently drop the coverage that catches
    # a capture host which never reported at all, so fail loudly instead.
    if not any("__EXPECTED_SITE__" in json.dumps(rule) for rule in rules):
        die(f"{template} is missing the expected-site absence rule (__EXPECTED_SITE__)")

    expanded: list[dict] = []
    for rule in rules:
        if "__EXPECTED_SITE__" not in json.dumps(rule):
            expanded.append(rule)
            continue
        for site in sites:
            clone = json.loads(json.dumps(rule).replace("__EXPECTED_SITE__", site))
            clone["uid"] = f"{rule['uid']}-{slug(site)}"
            expanded.append(clone)

    interval = group.get("interval", 60)
    rendered = {
        "orgId": 1,
        "name": group["title"],
        "folder": FOLDER_TITLE,
        "interval": f"{int(interval)}s" if isinstance(interval, int) else str(interval),
        "rules": expanded,
    }

    unresolved = sorted(set(UNRESOLVED.findall(json.dumps(rendered))))
    if unresolved:
        die(f"{template} still contains unresolved tokens: {', '.join(unresolved)}")
    uids = [rule["uid"] for rule in expanded]
    if len(set(uids)) != len(uids):
        die(f"{template} produced duplicate rule uids: {sorted(uids)}")
    # Grafana rejects rule UIDs longer than 40 characters, and a rejected
    # provisioning file is fatal for the whole Grafana process at startup
    # (observed 2026-09-19: CrashLoopBackOff on a 44-character per-site uid).
    # Fail here, where the author can shorten the template uid, not there.
    too_long = [uid for uid in uids if len(uid) > GRAFANA_UID_MAX]
    if too_long:
        die(f"{template} produced rule uids longer than {GRAFANA_UID_MAX} characters "
            f"(shorten the template uid; site suffixes are appended): {too_long}")
    for rule in expanded:
        if not rule.get("condition"):
            die(f"{template}: rule {rule.get('title')!r} has no condition refId")
        ref_ids = {node["refId"] for node in rule["data"]}
        if rule["condition"] not in ref_ids:
            die(f"{template}: rule {rule.get('title')!r} condition {rule['condition']!r} is not in data")
        for node in rule["data"]:
            if node["datasourceUid"] not in ("__expr__", DATASOURCE_UID):
                die(
                    f"{template}: rule {rule.get('title')!r} uses unexpected "
                    f"datasourceUid {node['datasourceUid']!r}"
                )
    return rendered


def build() -> dict[Path, str]:
    """Return every generated file as {path: content}."""
    files: dict[Path, str] = {}

    dashboards_dir = SOURCE / "deploy" / "grafana" / "dashboards"
    alert_templates = sorted((SOURCE / "deploy" / "grafana" / "alerts").glob("*.json.tmpl"))
    dashboard_files = sorted(dashboards_dir.glob("*.json"))
    if not dashboard_files:
        die(f"no dashboards found in {dashboards_dir}")
    if not alert_templates:
        die(f"no alert templates found in {dashboards_dir.parent / 'alerts'}")

    seen_uids: dict[str, str] = {}
    dashboard_data: dict[str, str] = {}
    for path in dashboard_files:
        rendered = render_dashboard(path.name, path.read_text(encoding="utf-8"))
        uid = json.loads(rendered)["uid"]
        if uid in seen_uids:
            die(f"dashboard uid {uid!r} is used by both {seen_uids[uid]} and {path.name}")
        seen_uids[uid] = path.name
        dashboard_data[path.name] = rendered
        files[ASSET_DASHBOARDS / path.name] = rendered

    sites = expected_sites(MEASUREMENT_CONFIGMAP)
    groups = [render_alerts(template, sites) for template in alert_templates]

    # Grafana keys a rule group by (folder, name) and a rule by uid, so two
    # templates that happen to share either would silently overwrite each
    # other's rules when the provisioning file loads. Fail loudly instead.
    group_names = [group["name"] for group in groups]
    if len(set(group_names)) != len(group_names):
        duplicated = sorted({name for name in group_names if group_names.count(name) > 1})
        die(f"alert templates share a group name: {', '.join(duplicated)}")
    rule_uids = [rule["uid"] for group in groups for rule in group["rules"]]
    if len(set(rule_uids)) != len(rule_uids):
        duplicated = sorted({uid for uid in rule_uids if rule_uids.count(uid) > 1})
        die(f"alert templates share rule uids: {', '.join(duplicated)}")

    dashboard_configmap = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": DASHBOARDS_CONFIGMAP},
        "data": dashboard_data,
    }
    alerting_configmap = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": ALERTING_CONFIGMAP,
            "labels": {ALERTS_SIDECAR_LABEL: "1"},
        },
        "data": {
            "rules.yaml": yaml.safe_dump(
                {"apiVersion": 1, "groups": groups},
                sort_keys=False,
                default_flow_style=False,
                width=4096,
                allow_unicode=True,
            )
        },
    }

    files[MANIFESTS / "grafana-dashboards-configmap.yaml"] = GENERATED_HEADER + yaml_block(dashboard_configmap)
    files[MANIFESTS / "grafana-alerting-configmap.yaml"] = GENERATED_HEADER + yaml_block(alerting_configmap)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE, help="checkout of paulkiernan/diff-logic-cells")
    parser.add_argument("--check", action="store_true", help="fail if any generated file differs from disk")
    args = parser.parse_args()

    global SOURCE
    SOURCE = args.source_dir.expanduser()
    if not (SOURCE / "deploy" / "grafana").is_dir():
        die(f"{SOURCE}/deploy/grafana is not a directory (pass --source-dir or set MSR_SOURCE_DIR)")

    files = build()
    stale: list[str] = []
    for path, content in sorted(files.items()):
        relative = path.relative_to(HERE)
        if args.check:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != content:
                stale.append(str(relative))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {relative}")

    if args.check and stale:
        print("generated assets are out of date; run without --check:", file=sys.stderr)
        for name in stale:
            print(f"  {name}", file=sys.stderr)
        return 1
    if args.check:
        print(f"generated assets match deploy/grafana in {SOURCE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
