apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-secrets
    namespace: paperless
spec:
    secretTemplates:
        - name: paperless-secrets
          stringData:
            #ENC[AES256_GCM,data:r4ADlgx4cFRfIA6IBLySV8IMZ8CEndgCBxQaEvrSYHIAuJ00grfaYu/tDj1qpZNVgmjz,iv:yJCuCtHGhShcsM4zBzzM8ceiP6ZhXGtDdTiXHHut/fg=,tag:8lnAUdW0OR2AU246xJ2xhQ==,type:comment]
            #ENC[AES256_GCM,data:ewmzNN8VWUq12X4uavMgiBniuwIUfCUBduMbpe1YYXeDmfvnu50wS4rkNsTRGy52gX0Nd4wucGEb0LdyK1D4LU+yKRkNe36CmPQO19Kj34cb5Jaa/bTC0gusj7k=,iv:FawhYIBNM6DhLjQuMpG89W47A4wchH1Qp/6VgOO5N3k=,tag:WXEIk+L3hxaVodvbi8JFKg==,type:comment]
            PAPERLESS_DBPASS: ENC[AES256_GCM,data:XDXmsf5yAarTDnxdX6mscGzIb2ZTNGM4fOnFR0bJnu8=,iv:Jsl39BI+8P7yeXedSGFuAxYly5Wh76LahMijOwnAv4c=,tag:sci7Q89+vtp2rks+QmIBmg==,type:str]
            PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:fNLCqn6zb+lAVdjzz1CyFed0WabV1tLQdp/5wJGbI21GmJitaiG82aFIUFjVKom8p+3IMdd+OBj77G4H3rSs76YTDqePO0i/UV1Vd3efqQWB7k1VrGg=,iv:5lVoK+dZ2jlhAabT4DU0pK7ExE9GwAmuhSJz8lSlknY=,tag:JojMtgIoeWpDsJbZCx16kg==,type:str]
            PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:vdSyqg==,iv:CdiLkjrTbPVXqXlufHEhJxiNl9TM4LaII3JJZqQQlw0=,tag:s0lRs2GTFIUzZGYtLv2A2g==,type:str]
            PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:SLPnury/t4jVhvigl7mZ6sr6Iy8xvo9Z,iv:gVP+APqSLm0D2JckfrsiM1uc4HQs24vMAZandoC3xyg=,tag:nhI51m630tJK3LUZw3lEDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaWtmYUVOZUN5MUlvUS9W
            eFgyUE9UQW9KZ3RxOXRmRzdPaU1tYjFaa0ZzCnRWbFJGSmxQT2ljMDNBczVzSkpm
            VjhJUzlDTUI0UWZEQWFZa2Z2d1A0bVUKLS0tIHZUaHlrb09nUjE2bTVvamc3YTF5
            RFhwY3kyUmZGbWRaM3J4YjlZR0VJdVEKC/4Nk5L4lo13LLIJcBUx/G+7yQg/8Hr7
            KXcqySLFpJzEmJakD/qeCaSFwKzdWUll6m2w7aA/LiVJu9kAcW48ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSERqc29CR0tNRFJScUtu
            OVovaW8yeFUwQU0zU1pCV2pmazRNMnEwZlNrClVFUmVyRUlyM0xDTlFMemtMTytr
            VGw0REtUNC9yVFFoTXlORCtGRFNSUE0KLS0tIFQzaS96NEpKS1FhOVFLaTc2VTUr
            ZG5uT1JUYWZXRjVaQkZpUklFZERob1kKCr0T25zfVGyijr6K1KPTjmAsiysPNn7T
            bc+JAjDdiqdp9DC6od4wGJ+9Fq95UG+7An9z0NasCSb739Gub65OTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT0Q4N1FudG55RmhsR3VN
            SFlaTFNtbklUd2lYK1ZqYXFiRmt3ZWxDb0dvCjNJNjQyZzZGT3d6U0djTE83ZnpX
            aER2cnd3eGtBK1ArRUZGb1g1RVk0bVEKLS0tIEVQZ01kWHlabGtpZE0yV3VGQ3hj
            R1NTR3R2OUZDbUVDdkQrVExGQWtMMjQKbumvaMkC7jJkH0ijHDREUi6dwfur9BvW
            f0RhI7ahyveonkyRfJYEjxYbV9VOikD1UYGqNxvHjNbxYceJJguNPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT2NvZXFXdThCWkhQWVBz
            ZXU2YU1FYUFtaDFnbnBCd3d6ZzdIOG96Y0FvCkZyRk9kb0hlOEU2QWxjU0JZT3Z2
            STVPZUNBcGRwU2c3ODVodm5Jb001V2sKLS0tIGNIWFNyKzlBZWhPd1hWSDQrUmMx
            MVBBUk9lZ1RHQmVqdUhYMEtvQnN2QW8K05h7rCUs2V1ZE0CLnwC4yvuZOItu3mBW
            IkPk5LFCX9kdPl/w/wnTpOUe6ZHpBaQhhQW79sBkOeVqntNIR9xuMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRTZ6SUpMYlRUVmQxbzdH
            cTdlMkNtSWJiT01LOHhCdFBSaWZoOTI3Mm13Cmd2bndaeGVYdlVRT2lGeWY3czNT
            SkgybzdlM1hKREhoMjIxc0xyck4wWkUKLS0tIEMvalQvUDFPOGl2QndpUWlxUUkx
            YzgrQ0h2NURUVlp2MXgwYVZETUZ0bkkK4KYnmGtSeaYzbsOcuzURj7axhlH9rrio
            zSrfCuJGTzEpJ5p7CZz4QiVzSwC6/XfKAZTY8KnzbQjQwhRcpJxv/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReTFrVkdrV1YrUTd3OERT
            STFiTVdzd3RzQnV3MXBvaHgybTdiTHEvZ0NZCnhZNlFjV3VkNlpzZ2J0YkhETXVy
            VXV2U202WGV6WlpkYzN3R3ZTL2ROWWMKLS0tIHJ2Y25iUmtNVGYvNUF6aVRmRlRD
            T0NWWUFVVThaYVBEYmlJOGd1Tkd5ZWMKqdMChI9P2/VyAEBWXiwW+YxvYFfzlOq1
            Ph6zJwpVPDJXRwzLSaC10T7BhL9n2bHttXG38J8cYNws7YHcH9cRHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWVRBK1J2V2Q4aUdQVXFM
            UTZkWlJRZ0ljbTVLZnY2MHJPTWxKc2Y3RDFNCkdBMDZKZFppc1B4OUlFYmxkNC9G
            TE5nakQvWFViWXAyeVpQNllYR2M5Zk0KLS0tIFhXMEJGN3c2R3JJTVA0OEV1bG5i
            UTk1M2hZQ0F6TEJYSFIwaWd1ZXo5T1EKOdGcFOBj/lVwmi91e15T3qRPrCsh6tif
            i/4f3AQppOAFz8IgpkYbU8kiToMZHaRNhXh0CKCgsR7JIWis79Wwrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T21:22:22Z"
    mac: ENC[AES256_GCM,data:3Eet7klgtDQZ0xbKtVQ78VfUTSVqup15dvVqoFchNRwMduH8lOMP38v/8J1vhHpIaLshr2HL1x1F9RhIXyVNHYmoGTVzdkb8VnthntgjB3UMpbGMLZF6V/auQm15449F0bFfNBWMzUoCwI3/2rUnQ2UN03/tpARhiszIryd6tF0=,iv:7jJ2GVPOBijibpljcXJ6rNYM6iRm8u6Ub/oMwICZfGk=,tag:DwIgqoFXtma807fDWys6Gw==,type:str]
    version: 3.13.3
