apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: couchdb-secrets
    namespace: couchdb
spec:
    secretTemplates:
        - name: couchdb-secrets
          stringData:
            adminUsername: ENC[AES256_GCM,data:Ph8y6jQ=,iv:MFYKE21xHVd9ANxRlxDj2ydimVss/WFOL/lc9oT6PCo=,tag:holUacOZG7i2VSIk7jVjOQ==,type:str]
            adminPassword: ENC[AES256_GCM,data:3uDy/OuI94jHbuV5YxlZenoudezN3IcAsFnV8j4BAw==,iv:EzaJTaoxvHNvX6Ikaiqqzz2vMaWZXatgBXJF5ASxwrc=,tag:5fBCsr1hVhyg3oD/2qQ+iw==,type:str]
            cookieAuthSecret: ENC[AES256_GCM,data:K1NkgWG20Se7deEBEEc5qiNTk3Xm3FWRRwzezxMPYaZv204WLOWJ6QSDAw0t+39wlk0aO6VhirWpZzLGE+jiIw==,iv:Bvb8uJwlbSjuq7Qiq2asHA8XxKibZiJhmC9PJja6Wks=,tag:GHv8Fh3B6bXVklKUEWwTbA==,type:str]
            erlangCookie: ENC[AES256_GCM,data:75G4ZxWMIHRhAlBywuWjEVtn6P+D87ug4s63mhzgnBjuVvuBcfd3NDzl2l/datjh8qXvaZrM+0RHbXKxmSFGtw==,iv:pgTUo/yhSZYSrUXguCsobbu8BC+Fq5zqI2Uf+ZlctGQ=,tag:alGDKqhAjdyLOuA5o/FdTw==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdUZSTCthdjMzUk5ZN0Fq
            UDZWM1hnWmE2dy90bjRTQnZMWnkvejUrYmpZCmgwdHMyZ3hDR1lXRTMraWFXbzJH
            eFVuejNJelB5UWZHUWZSUWQ5S25abncKLS0tIHUwRUE2ZDBkZWxqQ2Y3YnBwVUxL
            T3RENytoTWlNUVZNQWFpUm1MbTQ0dXcKT+kIKNrY50+7whyh7TZuIeX82EygJkOa
            Qv/DUnh7a5TZWU3h/tqX4uvNHlEQsn+vr1D3Jqz6+MNyJVo3otSOOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobjZCWmg3ZmtKRDc5Mk9a
            ZFVleVBYWVRZb0xnR09XVjR0bU4vcThYd244ClJhaUhGenlnNkNveDd1YnRqVkZX
            N0VnWnV6Mzh6V3ZlbUkyMHJWTHJTV0UKLS0tIEc0bE05TnRyK3lQSUsvRjdDVXNw
            bThyT2VwdmxOdWM0QmIzb2RjSFR2VFUKPf4L4tkpAR8KdiBFugkfKa7kq8Fx7O8W
            w+K1FZumRIOgJzO6+b1vX8YmR48h6ffhOulN5v3vv/u+fUoBLwAF+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUUlSYWFFN0VNQ2hoZmFW
            Znc1Ylg1TEZ6dTVuYVFRdmo2YXhUbXYrbTBBCmFHZGZ3UHZlYTRtc0Y3MEhOTWJi
            d1hhT0ZDRWozUUdGREJxdlNHbXRMVDAKLS0tIHFoaHdEQkxNa2xkNVJWUE4rbGl4
            SHhpUEVFY3lKQVBiVTNmUEtoM1ZLdUEKBRRcongxADL+CTNFbcMsEi22TVbXgjqS
            eAdHbJ+Eonx1r9fWu8WZ++2CSZYRkuWPwLQ4aAR1o/JWIVVp1Slq4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TW5aVXJDaFR0MEdRTWFR
            L0I5aGpHYkxPdmM2QkVWWmRVRmk1clgxU1NZCkNyOXpOWE1oenBiS1J6cHFKU0Jx
            UGNvTjFUbmxjUUtYWHp1MWpnWmhrQ0UKLS0tIFBxMjJpY2dxNVNMUVdnWXhrRzYw
            TlJTUzJYTnNSNkFKOUFENm1LblQ4dVEKB56uaAcGfBuBR3s4LAn957si2tUeDYnF
            9nxcOvl7W0YtgMV3JZmAKhKjdzw1naXl09JWpc2fBiG7hDCKYZpWWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdnF5cUdvVUN1MWtBbXRL
            cHZWeFNrMXZOM1RJK3MwQ05idWFoS05jSlJzCkhsSGRQb3ZFcmdaaDdxeXp5SDhX
            aXJTRVFvZG1Db0s4QmYvQ08xcHBIMzAKLS0tIER2aTNUSEt5TjVlNTlxVi9NbXh3
            RzdjdUFleFB6aE9oMGltNTh6eUxjbFEKLiL+xvMh6cq/LJ7O5Zjo74fPCErKFO8Q
            xSTHXQzeFca3yUEbEES1+URYz0x7SNOzumBcidNRIC5wh7SxuEhkcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMFFOU2FNbzhpZXVVdjFr
            TVZXR2NtOWNGOHlXRHhsSEFmUVN5UEJLUmljCmUyRngwTXVZdGh4b1BLeUtEM2tC
            ZGI2Q0tuOVNSanJINkc0K2FKeVNQY2sKLS0tIFJVcnAvQnEvTDY3SG5YZXY0UFVM
            VGQrOGFoMUNZc0dTLzdVVDRzZ1IwUmMKBtYx5kl/kqY5La6/c1YIWu19yDXOxuzw
            Dt+jakbtF0mAmK6Xru95UjcOhsMkT4mQ4higs/XRsl+lvr+HpVGCJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMk4wYjRYQktXNFpNNjZQ
            a1RCNlZvMEZITVF4MWppQjJRNUV0dUhEcUM4ClNEQ3hCUDZ6TzRKUndvazR0dkR4
            L0hFRk1PdHc2QnczWWNEcFFMeWVXZWMKLS0tIFExZFRtRVZHTnNRVG1zcjBoU0N4
            MDJNWGt3aDlaZXA0YmV3blZUMDFtaEUKzaWXlZDyjnPoYUFUQLsfDUnYUo4FNf4R
            KMr/RZdMBHKpDscatpVA+/4mxNyZTX2Z8b//o0qqZy1epF3QRKalJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T20:06:10Z"
    mac: ENC[AES256_GCM,data:8Ib30AXA9qTAt+Ql25J0dptKKqZ3jWGF4zPbyr/+GiOi+G+ddjM2uUQB0hCS4Y622KTFXsIgOf3X9roTNdN0aAL002TPoilmoYurtzANSGO7dkNON8JqmR9Kd8sTzLEFkXT/Uo/bJbi8o9btKlNh/F7KlCT/IyP8Uw+EsbBJkxI=,iv:bLs+WsqLsDv3+rPJyVcWApgUTzgIrfMFMbJDDcSZ2n0=,tag:+7/dhI5flWUY32b36XlV5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
