apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: couchdb-auth
    namespace: couchdb
spec:
    secretTemplates:
        - name: couchdb-auth
          stringData:
            COUCHDB_USER: ENC[AES256_GCM,data:SRiNgZc=,iv:NXkR13TtNjhKdiwoCm/qR0yV0ao6BWQFkbwDALt5UjM=,tag:MuF8eaKo0T1dobIV2qifvQ==,type:str]
            COUCHDB_PASSWORD: ENC[AES256_GCM,data:Tl9CyBBgfznQTAaDEy067TBBseeKFhBn4TdS9Vhj2w==,iv:3a8nbYW4n0vpczFnAJ0ZfgExNqfFCKqQnIVh6XXYcxU=,tag:bVDNDxtD9VppUW5F0iTADQ==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTTd6bFZpekJCNWoxZlht
            RHFCNXZ2R0w1RXFhL3hPQStoTHZuVmoxN2dZCjhjWkV6bUdqaHJFaEFaZEhpNHov
            V29Oc2tmQXZMb01UNTIwZFpWeWhRaDAKLS0tIFBlSVgyaU5yRkRwcFY5ZGZJUDBK
            cEp5NDNleEcvRGJHV0J1Y3RCV1F5SEEK+FQZFpcLqBA+QPveM/BLGA3qRtfzXMDp
            5mBW427M8KqvBikseq6F7SdcVAqRzDjM/CkW62q3K8rOZvliDWOwfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c2JSZkE0dXU3dkFlQXF4
            M3FDK1krcUFaMGw2bmw2NHBtelNKam05NGpvCkQ1TW9XQnFQNjVtTlBRc3VoMXNq
            cWQ2MW84K2JNM1lsWGoxK1RGeGl5RWMKLS0tIFlNMjdXMmhUdDZQZFUzZDVQY1Rp
            bytTZUtkczZ5cVd4OWUzS0NPSEdSbUUKCqharDyMydQYj7GV0CePyAP9szc5dpyQ
            XhqxN2R4Q8hLSADJIW5emUxLu3+E79wYir77HstdzUzi2v6MVn5UtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eVVNYy9Mejl1Q1dEY1JS
            TDNZVFZHWXJMME84Tm1HZWNxMmRVZTFqS20wCk8xQnkwcXJEbm9rdGZCM0h0dFhL
            YThaNTVrUXAwVE82dXQ3cjF2WHRqNFkKLS0tIHZMVU5PY0wxNlVMUnJCMk1pSEhU
            TU9uOWJRQlJOUm5QMmFlNVBjRHU2ejgKmNiOXC9VSsycWLpKiAD95ytBidXL2WcN
            M6+oEIWrHAL+sdRIe+kh8d2qHXbMNk8cC2UEysZPCPSGiG594gOBjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeEVQUnpPSitZNUplaTF2
            a1ZveGRvUGFsQ3BpRC93RnVmQWdkaFRjNlhZCnNtMk14UVZWK3hqa0swMVFlalhG
            Nkt1RmpqWkhHZEN1alpBd0wwQ1NHM2sKLS0tIGd3ZnlQWDNyVnZBRC9RNlgwVUFM
            UG5VRStxbTE3VEhsSldCelVNakZ3MUkKbVDnBgVD1WRfNDf5UYjJBpwuE0M+iUH7
            HG+8OhL6MnVI8mKw5+RYAlC6irjAEkigQHkgxiJW+jXFsCbKd2WhJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZDdEMS9KTnIwL1E4UEZG
            WXk3Q09VdEZPemIvQWN3bVNSNFgvSE16VkYwCnBoa1Arbm5FWkxQYW8wSGM3Vjdo
            L0ZIemVyZm4ySlhkSGYvRldHdnljMkkKLS0tIENpeEZDeGEyb2RNNDZxVG9mZEtr
            MndzTEdhbXNuTzNwRFZQVG9heXpBZG8KcaNZb1u6DqF+Vj5u2xb2CM/roGuVQBG2
            1LafjCWyiNhUJCEGKFO4WVToEa968De+n4TnER3mRf0WO0NApsxd5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSXF2Rk1FakZKcVJRelZx
            VlNSSTVLdWxvU2NBMEczTnZZVktObXZlb2xvCk1OTFgxcjFOZy9YakhqM2Q1NDND
            WjRTQ2RBQ0Q3SmVaazYya1BUM0VqS0kKLS0tIGVWMzdja0l5WUxud2NqOCs3ajJu
            Y1pUYzc2RTE1QzlQbklmR2dFRDZNcWsK0+muOMo7tTWdZnad4osZ6jZO9tqGmSSn
            MAQRqxZ8yQvHPT/8J/Gw3piNyclCr0Slv+sEuRor0rz8pIHS/HwJDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZytiWnBmN2lVZ0JFaEtx
            OTRmWDloRXExSjBiS2xtaDNnaHNlcXJHb1QwCkF2NithYXZnWUljUW5MWXIyeFFl
            RVhHYnVDcmE0K0pSZGJ0VEd6VnlBazQKLS0tIFVTRTVNMDNlK203bHpwQ0d6WVdU
            eU5YS29wK2ZNS0w5RUtJRGpaVEgwcUEK43Z76zlNDYBG+Y3fCqgLazFbq1E7tYrl
            5jmLuNw30fR9Qz6Xs5k9U1sceI9QWKJiDlqF//wto6chhZkdXrx3Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:57:33Z"
    mac: ENC[AES256_GCM,data:O5FguNkHpFXUxfZe1SEPKkASbZeNVUEeBX2jTK/M+T0b4oVHIq0enSbEYVvUncwOcRs+nuE9jm2Ufz9BEHQYzxpwSmLkkSFdmjMYIuyNPqDCElBKY4h4rzzflIDXIE9siJuoly+KyUWrWndCPYR/rxeUgJ7hr4gv1fLsfIG7qCs=,iv:b7PBZcDXjqauOaeqyPzuMRWpBQnOlNwT8Fm4ljnoYYw=,tag:+zbGZP1VnGEyZmOLQ/mdsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
