apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: local-monitoring-grafana-admin
spec:
    secretTemplates:
        - name: local-monitoring-grafana-admin
          stringData:
            admin-user: ENC[AES256_GCM,data:1X7iks8=,iv:P34bji3Jan2xpV+HpROtlhPwYaRjMq3gHS6v02eEhsg=,tag:ZJxE/UR9eWw9+uOvQOWkVw==,type:str]
            admin-password: ENC[AES256_GCM,data:Y4fXTID2sMdX9/Lo2a8yoP0uDNCR2M5LhJLffWj4MrfKpcd5CE8tkZTC7A==,iv:TVh3k1KCbA4EbWZtkr2A7p/dyh/EbPThNMwEsiAtXf4=,tag:P95CxbHvdiIFqk1n/WN75Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ0pIZjBtY0JSbk5xZ2xl
            emRsSXJwaFIwcTR6MjIrejlBTUR6a0drQUdRCjcrNURXVC9sNGRza3dib0swdmx2
            QUdSNWIvNWNHZjRpcjJJRWx0ekMzb0EKLS0tIDVvU0lQQ1N1MHNDV0RNQ1hzQndw
            QkJCV0dONXczcDd6eDVzcTNtaGJnd3MKer+gK0ZyrYcVKF9mRDbasC1p6zbk5FQ9
            fzUfHYOXB+uP9U0pZkEvxqx7uQN3hGvgaSdO6qszB7GlvqaXqSG59w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTG1BSWhrcUxFUWtHUlpi
            WFh1MGVPZHJTTGhHVFd4ZlliZDJRTGlzaFU4CjJKV2xTOWsxWERlWXBVaTRtNHUx
            MVdwU1pXRk51NERUVEpKSlpaa3dvSzQKLS0tICt4Q2ZSQWZ6Tk5hTG4wQ3Z0cjNF
            Wjc0WW55c3BlQVFPM1dpQndoWEdJTjgK8dZFDL4wJ1MdN5ISCY1yH4Sb+Ia8V0KG
            dz0xHIVSyRSWEKViuPkKNzmEmpoRBFAUJa5+HvWYEA1/foJYj7gj2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdTFzdk1PL1h3QWJkc01C
            WEdBeVNlU1U0a29WTHhXamtPM2FmQU9jbkFFCnZ0c3BWWDlDbW5lNlF0b0tPYW1I
            ZTc4RkN5RlNRWjVnVVA4WnU0NFJHL2sKLS0tIDByVE1HbHFKU2YyazhZdHUyZm8y
            ZDVuYnZIR3pGdUtleURiK0Q3NlRlU2MKpefdxl2Qc+yoXO/A/VmE8IvERJmybPZY
            bHKWwc9b+gYsJELHsNMop3R3B4RCdO1uR+Q3+H+7SGfilIVmmS3gKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraHloS05pQTNwRUluVDVz
            V0NEWXB5SGE5a3pzRkFkMDNkZDViQ1U3d1dBCm11NTdHTHI2ak1JTzRyUGdQcTZF
            R1M1QVdNV2dJZzR4STd3UVEzQkVBakEKLS0tIDRYQi9ueFUzL2l0L0Z0ZGR2WjVL
            aXRBd1VXcjZpenBBOHVXUFowcGRvTlkKEHpEk05d/c1a4cMJ03ZBrx248f0J4SKu
            70vxsKWT5Mh4mKQhoZvh6JKcI4WEdca4wpUfjdzZAhUYZ6C9zxO/vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZk0zc24zdktCaGJCU1k4
            TGM3by9QbGVDZkczYWVOMDlLMGRVN1ZRSFh3CkQyNGNhZ0JMd2JkN1E2SXZoRzJ2
            VWdnL1FaTnNHRGlCa1k2eUc1V3IrVmMKLS0tIDJSNUZnVE9vejNqbllNSlQzUkdT
            SWtCbnp0SjR5WnpUd1p3aUVvK3JDeUkKBzBspEubqlu4/UMAGnIKVwxVpB1CNx/A
            yQ2WenA0q2XH/Kop3s4znMAMpWFfuyZfkfoNizhTO9QPYqUloCE0ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSlBGcldVUThkbnBPNkc0
            U3RxTGdNYUdxdFF4NVU0RG5CdzJmdTVxQ3dBCjUwMnI1NkxIS1gvN3JlUFp3Q1dY
            eG9XUWNtSlVIRDVrdnJZR2luVlBkS28KLS0tIEx5UmlkSmhSRGg3ZUJ4aEVpSUxH
            S3MvNW9vRzhKK2Z0VXJncDlCY1E5aVUKguHJ23B4Gh0He4bXJTP2yJ71lT5XjkKG
            F9vbobJMYnDtqbP6vw8tingdWVdExZTNkpNCNZytNOsAKNoxOPkI0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVFTL0hMT1czNm1JTlJS
            eEh2VWtsZTdnM0k1N0ZnaU9BdkI5YlJ0Q0ZNCjR0SThiRDZsUytEb0dETzlTMGwr
            bWJ2NmtKaFg3K3VaREUrcWZJWVRsTEkKLS0tIFg3SG1uZ09VMDlUekt5dDlvUUxu
            a0RySUZYQ1NkUkxRSXhKN2h3b0lmUDQKzv90zmU7xAnWiSxe2bdw3G+MsoDjHjMn
            QSkwiTTbQgK7qj7PY84hBjRCm59mcnAXmk4ix7l5hFBs9v8YHueSUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T02:53:58Z"
    mac: ENC[AES256_GCM,data:mhhR87rtv9tVmKGIu+gqY9ENMVgMFmGo5Iead77uVVWrqHO9aiGzW4+FBOBITV42ftw7vmT7IsbJ8lj89jEE02oY8w8SnGk3lJuYUA61jAEMEb6DUk72ncD1Ng93H4o0d6m0wVwQ/oXt3rOcXUqrKGxqGyK9iLPGozSduGXwrgY=,iv:U98wFVqMwo+xVzN7CrD9CloEktsqgdglzonuVXFIdaY=,tag:2JwO6GZbeLC+yiSoYDxSQQ==,type:str]
    version: 3.13.3
