apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: local-monitoring-grafana-alerting
spec:
    secretTemplates:
        - name: local-monitoring-grafana-alerting
          stringData:
            discord-webhook-url: ENC[AES256_GCM,data:51SVd5Kg+LS8xACVW+TyMLADe4zQO/WGEsIytTaqTh2nj4U1hUnU2fj7DzN318XkaNXvEKIWX1wNBTKcN6n775NmYND4053w6k6Bk3V9pD8CroLNYu+xi6iLLcYlft6MbiDaXzAmS7f7x6hjJqefVJsGwZ4eNOh2Ew==,iv:2DjbI/ii7zlxnNE8q6zvryydrimc1xj6ZXU5wy3XHbE=,tag:dzDLnxDFTl2N+8xYOzkgaw==,type:str]
            discord-cluster-webhook-url: ENC[AES256_GCM,data:UXsi71Mo/ofBsQ489jn6MJkiGUStlJ60x5dyaYnbEQloXQzBn/FW1M5CHGL6qMKyZYPYK7bpQpfLzet02cm52WraxrXNUzukm3CQOi8eOQ1sfOon/3S8aYnZzm7/oUVEjv9G7CAf391WCLp9g8evwxgaOYiZxCKoaA==,iv:kBnoOka0Zl28/KTDBo0EQDa46xb7abQGKIcZ7yhV1Ug=,tag:DdOilqbkHq97Fn20dSgysA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNEx3dUZmMW93ZWJjUy9o
            TmNHUDRpdVdMT2E4QzlubGdwRkVFUnpEcWgwCnc0NVNuUm1tUmNZalZJSDJrTnBs
            NTlEWTl6QkdOTzZZSlhRTldvaVU1VjAKLS0tIG9xdzhnYUVxUWdWTzJlc1B6UDl4
            ZkQ4dFVoOElLRTc5R0VuVUxvV2hrQ1UKDg/SAFmJ+nDSCGd3z5rK40ThCzOoVcqv
            IVPI5v73s3scCaye5jmagfUKpJUPl/jflABI4pwjJQ+s/l+WEbUyVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZTdleUdlNU9FWEgrd0NG
            RVhxMHUxOHF2ZkRRNGJEaHVSZDA0NVFOV0NrCnkwR0h0RWhoMFB1L2FnSzVwZ2E4
            NG9IbGdTU0R1dW5OWnRTZEJRUnRpb1UKLS0tIElsUzBDaDBwZzk1N3kxQTRheEhM
            d3NoWU5XUE1oS0J4bXFSMks1STYwdm8KyIfoHCerZ02waUci6WFYYiPLUtRrlRi3
            nq2lr93KTwlpriq3gAVj0WoYN+oytY/EKZguVs/vZJBj/LE5MPAaDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqc0Y2anJaT1ZBMmZBMFl6
            WnRGdEpuRU45L2ZrQlVGRHdNYisxWkVxdml3CjRYd1NMVzVEVmhqbnlxd2Z4dmFv
            MFRzOWd0VVNIYk5UaXFvS0dsZzczU3MKLS0tIEIxSm4yVlZkNmhXaDNONE9IRU94
            aGNnK0V0U2FXejc5bGlQVkNHOEpRb0EKy81WRjlmA1PsweqeVixlut5CyMnDoa8A
            rnVAsLcWWT2kThlVAFicfNudMuZIGwQzQ0lyTzR3XctIS7Jx4YACIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOHQ3cnRrd2V4cU9mUUVQ
            R0Z6dHVhOUtwNTE2QXhrZWF3SmtWNWtNQ1VBCmxwbzBweWtGY0RYYUd2TzkxeU9v
            dTZqcDlmclNKRTRmemc5T29KMkN4YlUKLS0tIEN4T1NZOEhKdEZQOS9hcjJCQXlj
            WW0zcXV1TVRBUWw5bEVBTXFwRjAxdVEKtk4i1TWjvzLtKf1XA7DJs5wtYpRhYUzo
            h7iweY/1gfFAtqiJewmENSgws7bSD9h60dY4r3W/tqVTRzVAww0X+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWK0I4aG5HRERDRE43WXJE
            Z1lNcFg0cldxMUd6WXhaek9Tamp5K2hIVVU0CmdMNE9MZ1RhNUdJdGRLSCt1NmJz
            VkpFRmJYNkV2aEZaTVNMSkxCMkR0dHMKLS0tIG43VmdiemVEVTNjUzFPQWh3ZmZS
            TWlxT2YzYTk2SUc0VG5lRUN1YXhFT2cKtljdf7G9uocCTIPsTIAd48+JYc/70oTm
            5lAnzePfDRLY5DmykpoU2ozvjHg5b2luOUVMYXXYreyzH+N4qdzHmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWW1vNUJWeGVhN0tWOFRs
            NEZVWks2ZnQ3WFl3RFRyemlXWmtyMzF6a1NzCkR2TGlNTVQyaUN4Wk4wSzZvUmxP
            bTRWMFh4YWxlOElPeldQaS81UEpWeXMKLS0tIDl0ZmZLQmhVZVl5WnFUNFZFUmdM
            Q28rcUd6dXNFNXdvVGZNRnFNbU1vcmsKZfvrtbX7fyZ7vSNIv8rSr/McBXcKu8ZC
            6zoR2cJcJlNKl0PrhZ23moXncS2QpnJWohO8bSVBByP9hZU7hExkIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnalZpb2xqMmtXZG83WENj
            MkVwMEJHVUtmb2ltc1Z6cUFYUU5Vc1ozbENvClphc1BOZEpXY0RMbnJJWjFRRDho
            Mll4QVFBUHl6V1AyY1BHWTN2RkNBbE0KLS0tIE1zWnRVTmtzK3drcEhDSjhqNEhs
            bjhFRmtCcE8yRmdDc1VhajBGMlFtcE0KVAYu6hhsv7ZxSx3bjDXPI/s4x3IMFffc
            5w+6xMn95zyOa/uKYSeJ5vbvNyKt9cypZzfcR7HfaO8YESZBwjGlmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T05:26:58Z"
    mac: ENC[AES256_GCM,data:rEjMbR1V0bjVGRsv64G3z8jIELH/zeQFnn3sVOcUYVmBFYxUOCf8F9LqcVB99Inq44J4QZRU5V2f2urQzpEPbWqXBGsKAOqhE+9fmwRaTBJjlzwf6V7WdjzYDuZH7U6GidF49GIfRDl5IC9BIxSQubjI2/f+bokLnj7RREg5iYM=,iv:TCyIivcljlpE3Tmsc/3rMkohfK1Re/CY5qxovUpLPvM=,tag:HSirjlTkhwWpNd9TjsUCfQ==,type:str]
    version: 3.13.3
