apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: market-measurement-ghcr
    namespace: market-measurement
spec:
    secretTemplates:
        - name: market-measurement-ghcr
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:jk/ZVPBlAbm2lOI0yWebTnv9XboeVT4NK3+fDOyh+/40V+/y2H4wgAJi+GYvlK7GYbOur6/tNLNJV4irOHGXQDBlFppKk8PHzOgvOSkvvu3i9dO0crVQ3GYsTnb+bTuIafHS8zLD0+KlRkfSmKFi0zE1YXdurcgRbeSi3+qMKQJ1bqVfOWXnYXkO4sQ9TXU7gFWEO56VEHUnjLaEIAhJCAw0UceKskuBetzoUAvgQlUjDABDoNyZ7Jo=,iv:XxA+n7QIIkjV93+1o+Nppb2Zdble72HrA0U/mTgy/pQ=,tag:xBnxLYrhVvVl7lX2VxLSHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NnBKTGQ1aXIvajFHZjZ4
            MDd5ZjZtOCtOYlpwVnJkcGZNUGxRcUUvYTJjCmR3TVY0Ni9hL3VmN0FKWmszV2tE
            UVJuN2x0MjNaZStvR3ZGcktseG9xSTAKLS0tIEp5WGRMZEQ5dkxRYytNMDZqRXNh
            dlFZem8yLzdNakdnaTBCMzRlQXV2RjAKNSouGiJ01Mn04bTvRNUw6ZDW0ZiBmOCy
            rJcSFFzRucwc0v2/JDCVbeO3ni+OPsZ9YDmFFwN4KUxt0w/DKgZ34Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TlExZ0x0SmpDR1BlVHJZ
            YUhzbjE1czZBU2szOFdEdFkyQ2JVNUVnT1ZrCkFFeDV1bWZjM2E1aVdKTXVPWlVG
            OVBCYWVvWkZKbGpwaDVGV3ZiOCtrMEkKLS0tIEhOQVRDOVIvdFphZnoyS2JzYndx
            dlFUeDdYOTZRVjRJTVFlU1VpWE5Cc0UKItO3+0rswAn34XpllH5DQazULaXWzxOI
            S+1HDcAFU7eYP3GAULQ0ccmABR90MbmLzmIU0N45gMYFKsz2Inm0vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSksyUkN5Wit6R1dDU1lS
            bkszVEJUNzBvYUo4K3RENmFNTTQyVnZJeGdJCjExT0hSamJ2c3JJY21GTldNWkM3
            NEF5MXBLeWF0VUx3S3Y5TlJya2xXZk0KLS0tIFNvdXpIVFFvZDd3b1pXU1E3WXZ6
            cSt5aGFRWlkyUGZQZVZ4MnVnN05xOGsKRO/aiESjnq/EwGwyKCjCY68kBCulOFpt
            1AuumUWI7ccwF/qpzVY/Szz6dXVsIib9lJLl8F3ez7KDwqfRID9Bsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ajJEd3RSUmJYY1JZMkpI
            UHhEcEJZam03eVRXbnN3UkVZTU12NVRzbURNCnh2anFuK3ZoRGRvbDVDRTNCSlFt
            MElCaHY4RkRwM0plZVhNY0RMU0FvT0EKLS0tIHp6Z1RlSFE3Q2V3aEUwNlFBMmdr
            WWw5ODRGcWNqL0FWVUdoeDlBZHg0SGsKK64/Nk8ZE3vII/E1nvNCOFFZys+fnE/u
            jsGMbAMNkV8j5YXtqI+hwLRGWl9Ig1c0rxAH/4A1PbiwCHOpiNWEBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSk5uUTVnQms5SEZtSEt4
            OHRyZUlpc2NoaE1MeXZ5VE1mMkp5cTJ4SDNVCjhWRnl1MmZsNmdNUHJzNVQ1NUEx
            ZHNBNGUwdXdqbTlYOEVJQWZTYmkvQ1kKLS0tIE9MbUNjMzZlRGFGenpGVUwycjRP
            UjE1UHdvd1V1R1llcnpVYUdiSkRGZlUKe5XH3gf7aG4W/+GRUt9SS/kThrpfQjOP
            nywM5RK2+t/hsAZG/y6A09CpqFUDSqP6F4/vwPxerXypT2v1BDplGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMK0wyN1ZRaVRTRlVSUXhW
            UUd5OUZyK3J6dVJLQ1hhQ0JaVUZGdkpRN1NVCmN4MFB3dEt2UEl1RVhnNVB1QkFS
            WUIrb1lpOGpiN0FwR3lWbUR4TUlKdzQKLS0tIFpidTlkek1YL2RsVXU1d1QxN2JX
            MHhxbmsrYlN3QjRtVGFCV0FQNFk1K1UK2tmWPf6UPOZulYCPvdmGrorzj1aNM1VR
            zQQqq1XYgIzpeF7lnzp4QmftFCudwnW6PsBANr8DuOqBaDS817YJaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlL0RkNHdWWXdhNFhhRmxj
            K3VpOWJNd014blJEVkY5WDNoS24venBXdXpvCnN5YXFYT0R5bzl1V3BuQ2QzZ1FK
            VkpCSDllYmhVWTdIanVJZ21tclZkUzAKLS0tIEprU2JGSnJ4THJUNS9BZTk3dVFI
            TEdla1BGV3p5TGw0allpSy95VEZURUUKxm+6qU2Pn8COwTduwYs54S+mEwjXUAxF
            7ohrUhR7n4CzKs3DKvmlFOUlRjVQmnAZme9Peua932Bxw7K7gpA+yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T12:49:42Z"
    mac: ENC[AES256_GCM,data:9SZiCykFyYc1syKpHrfs70R9ZmqIanx5sAn2XPbxz3UtDeL4dwhBqeVo7BXzsKvo0krbRIik+YYsk55waeqDwPkWhgj8U6wFF5XAIOLQwaJCO2eF9bdfD5brbJ1wvdpfJ66nJtZeylHRvRry1+OnlUE/PWQW2h8gDsSyyWI1pmY=,iv:GehSvFtHS9df91cRywwx59Ly420y96Q0/mJf+luUimo=,tag:Tzw9BMRRdHWNz2+Uap5qUw==,type:str]
    version: 3.13.3
