apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: market-measurement-pull-ssh
    namespace: market-measurement
spec:
    secretTemplates:
        - name: market-measurement-pull-ssh
          stringData:
            id_ed25519: ENC[AES256_GCM,data:0Cj8XaX9lL0zipwObW++2qnk0W9DCeCoWQzK69OTgO2swmQbzBl8Yc4BN/We5sURlfdqThSxqU1cbOqCz8mNuF4NS9joVkLeUz7pFlPVw+vBme5AJWiT5aqTtHA6SK0gtPvJRDyew6OhfgvUQCtUZitagmFgCeb0W9fyvnARNdRSlmWGYEAEyXDRSP5RDK3hZl04kYVsZ6gK6GsfkN/2Smp9yFqg+MxYN8C53HRgi8O215CCku0ykOxvH3678FaGxI+GOC0gFFWTNC7dXx/h98rysronjzevxDGcdveMVhc02niOCzq0PqE00/WFbNi7OnYou8e8fLaDf6KqRkGCNHMKRRn5aXuKoKvm4/wTLo8wXrYQrsfA4ux81EbAyDdNccMd1dl5PzHV6BEEY2VyBAVtJoqfgjwsQugqcqqH36sKW4BEDoUq5M3GEiYHE+LIHpkP63Fd0LWxRIzkNBWb+5LL/iELQzgn7GRO6C+/IDJI6C54U3c7TzecfahCgCf6c3XL0V9QHEenlWMyC2Qli6MJMK7wLH3D++n0Wqwgi9DgCGasDExymCiRt6+WpSPtBGwSvKIyyx3+OR8y,iv:n/+rzA5xgbheHngTkeyfHc+7sigITQGf2bBP4Tr+cAQ=,tag:AIdvXNIFvIJcPA8pFO9F6g==,type:str]
            known_hosts: ENC[AES256_GCM,data:iIVCpUyRPlA/iJBJ1upk/lqqOMrUABV3yM9ouUs7ebkYuP2UZV4vrYidPELqybNvBhJGkR8kxfE2vE4NnX8gOPV6U6hDprviWAolLMSxLLe4v6KgP2ndKe4HbsyU0vKWESaVjCummrUHRoi6duxQg8Q5fwL35mG0Zih+9TT0s3h95GGRTT0avjEZs2kf9v2TnN/FZF8HBmM+sYHY/JS1InH888NfH1BeUv2aB4AXW/v7aqfs6MTb+bks+ep9nOc+1eGXoTnQkdyfQMTPyOnsF5d1WMViMCQjKKucqpFCFSoIzPm7AWPCJ+dEiDHx77Pw1hN2uA0QzEE7xumrXduJBM4bJm8pjfSgiBLVDIcSVqSXhlNFoR0JnRS/iDNry6hzF2EAHkgDkE4Eab+Luyb90o3P4GQxIXizNr31NeojPmiQWNhf5Wlp9o77f97asfiV+fVTGEoFMgLB1Bu4Q1JCO1sH+lvB96/XaqRb113RxTz6pAZvhipAZES1BB87hFvfrm8TmOMRs8SvdRcJuccROzzV7Ep8FV/32F3vueJIeE++uSeClnSAJqnTOK+2Avam574z8/8FbW3jxP4kyKbAoxRICSlpbJFfWDAcpPVt90FBprkGe1+qv/ztwGHtRnBITZcakUrATnxXm08vx/Bs0cW5sZASkMEYGByb4+voCcAGqHVeEk8SgkEQiTkhngX1BpgCb6gb0KGFzAa7KBx2wAHwcAo23GBO+81b+jC1vkyn6aVNIgKrj5VwLrFeETWx8uDW/AQnrkl9LeP9etFesJZ++PHNcmOXf0sIKLRJuafqUNg1r88MarrFdAxOr3hGR9JRLmIoXxxnalDeU36vMAxJR1gZ6XyzaMaXb+jQSi+6u+qxcPnBkdfRZbrYhx3/0XQ6w5JrtxemFUekhHWzUqCcvBmadlzfH54PTn+9rcso8FlBIaoYNBtuns6dgkzoC/8pyKbAUkxFeWBI783poxhWwPJkk/Wc6m4mBCMMcLEFjeUQrkUwC2X99J0Tkv4U/7hIAf4hkaDL3LxQttpGTt6IZJrqhCuMjgDYjxDQYC/+92TRqInLYPFt1gbbsiLwud2N5AxIEb7Cbn+2COxl2tb8K+OUT/MU,iv:M4qdgUzBkLdSYNhvKSCdKBRm6W6MW0KWtBLKXTKBzg8=,tag:jZwaAFi4aS+07s3yTWmWjA==,type:str]
            remote_host: ENC[AES256_GCM,data:Jlx8qwciHjzEhBh3F08=,iv:NBVKxa6X4e8NyJpddEvlqQpbIlLxzM5PLAX4smW/3os=,tag:HmaoEONJisTXm9pyrASrvA==,type:str]
            remote_user: ENC[AES256_GCM,data:KTnh+9LvtjEtY8M=,iv:OgKK5OvghH8iAreLC8bFu72aUlFevwEV5MhVnqnU9Kg=,tag:eEuyILoI8UXc+M8dapUqGA==,type:str]
            remote_port: ENC[AES256_GCM,data:3nM=,iv:Gwsli/kRcTPnFT8vv1aN5IeNtLSUsh4wC4Q/at6W7bk=,tag:yW/lFnVUVTELdKEHaKRsAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNDdPUStKZFZ6aURQS083
            a0F4dmgzaWF3V0xoYk5HUVQxZmFsb2ZWOFJjCk8yMVNKZC9Zb3V1bXhqSXFQS1pu
            bzVUSEpZRm05aklkR2g4RHBKSnJHVW8KLS0tIFcyNTdvMzhDUTZkcXpaeStDOEVu
            M2c3YmR3d0FGMkVsd2tBNWpuN2hRSmcKcL0HAbOzOhIhCPoeetThyOkODCg4aXEq
            Pf7tmag0IwojbKm3r71rE4oigQ3DYyod1NudpkULUmfZJHSqf84ncg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSkxUSFAxYjhSRjFYRmI0
            UG85a2hwcnNZY0xZai9sYUZnU3VkeWhUVkNJCk5wUEl0eElOZm9UeGZUYkdJK3dq
            MWVDaHRpSE0wbVVoa3BPWVFOa0JlT1EKLS0tIEF1NXdMUHdtT3FoVFNCQzltY3Rl
            dTNsSnQzcDJ2c1VOSHJSK3hjanZVK3MKjQyguNxusLv1FPd31G6VgTouNv4Pxvv2
            E2pApxDjkHXBT60CE8zG0DjPSygJQQmIAK3DpbxIxqa3xkIj7HNDPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MHVmQzgyeXpPVHNKbzh2
            aENJN0lMRXFuVE5JK2p1NW52RXg1K0dnVDJBCitDQmtPVnNxU25YeldSaWdlSFRi
            U2dEelkrUXBKWnVzaWlNOXVYSGROVmMKLS0tIENhaE9GVi8rRDU4c0pNOEx1RkFY
            UjlJMzVDblNZVU9YdWRXOVFvOUE5emMKpVvJ4+Grib/IIVcfpFpSLxhzieWwZUD6
            7ak15RcC+LbNTMbs3IU87IIYoS9LYFQa9UAU1MCFv0r6n8haooZnBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTU9EUXpqaTJabStHNnp2
            U2VkNXFaNkUzYlZCWDkxVXRyOXBPMlIxNEVJCm4wVDZLaW13SVEzbVFxMllVNHdL
            b24ySmNjUGN2TmhnWGhUdlBlOHBZZXcKLS0tIGNvMzdJcEQ1U0VSL0FxZ2RZaW1i
            QitUOC9oNTFGYTgwbDc4Ri9FUWpBWEkKUJZ94MOQRs4ydxb+3DjVArG/WOFWJSYf
            KfeL+YRujaqCXYXAax/2AnsZo19tbb2X7bz+VSPQjw0Zdon0AXxPdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcUdFbzF5L29vMlBqN0to
            R1FqcGFEUTdLcGd3ZVd2aXhSRkJlaTRUV0Y0Ck1KN0RpM3pObDUrTit4Um9obGg5
            Q1EwWVRTemtoN01qYktOMVlFME14TE0KLS0tIERPanFkZlV5ZFIyWFRkdEhBdkZy
            T0FLU2dZeElJV1V3emlRT21KVUd6cDQK37ZcGrTy+Ri63KCvwAT6hKrVTYDiWAu5
            GPhB6FeLxUfDiMJoAPsmCpBXeIFweR8IZX/pvsHKlQqL0hSsinPAUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwL3pPSUVEUjROVU1ZN05y
            dUIvWmFGeE1pbDllSE01YlFLenM2S1BFRm1BClMyNi9NZk4yOUEzNGk4R2xEdjd4
            eXU0d1ZZRjJsbUFMTWZhM0p1S1VxRncKLS0tIHR1ejhMYW9pSlFneVVKYmxrQjlo
            K0g0UmpzU2dFbTh3RmtVTDIyT0I3N1UKPfX+/nxlCwLakafbBUd6TGFJRtpyekll
            w4CSyJPUQczgNns3qKLkRdnGdXbo3BbtdeRPMi+P6PN0c80ABy233w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QTlnV0xOZUlhTU9jWStp
            MDZJY2VFZ0ZPNUVCS3hSanJ5d1BYV0ZRK0dNClM2TWt1VzJpSnNRQ3I2cm44ckJM
            RTZDOWpabkxWbU5wOCs3R01QeGpjU1kKLS0tIDZLakFCY2dRV3V4T0k5SjBYNHdJ
            bFB0dEtIVXlwQitGU2tqYXlJMkFGK2MKgIPiTJpbJfD2hBtWGqnk+bnpwzwDfGTA
            nXThArk7nEZfymLUgLYgCRy+7PLfmz0alaTSMv1pKKxKxWPAdphT0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T17:59:05Z"
    mac: ENC[AES256_GCM,data:rpvSL4OFz9tPlX5OI4Qxb0PYhaZML94G3RW3KHI+v0/eDPq16Sgpi4h9/UbWMPXtijKetd1LDqmMGbn2OKrd5EJIjmPTkiB6vhurSZfat+6iP2RohhH0l/XY1zdyh3Q5C+ctBO/qUQJUeTWYzplV1ru87f00McJXP0rmzp1NEHo=,iv:eCafCINLJBLImSUbInbzHxp7x9wNTH6PaajjP46Tsqk=,tag:M7ECiLV8FlOYyKH9joFqHQ==,type:str]
    version: 3.13.3
